/** Frozen M2 paraphrase sets. One batch. Do not enlarge after seeing scores. */
export const FROZEN_SETS: Readonly<Record<string, readonly string[]>> = {
  "p1": [
    "What did you decide to order?",
    "What did you choose for your meal?",
    "What did you go with for dinner?",
    "What did you pick to eat?",
    "What did you get for your order?",
    "What did you select off the menu?",
    "What did you have for your meal?",
    "What did you grab to eat?",
    "What did you end up getting?",
    "What was on your plate?",
    "What did you take for dinner?",
    "What did you settle on ordering?",
    "What did you land on for your meal?",
    "What was your choice for dinner?",
    "What did you opt for?",
    "What did you have last night?",
    "What was your selection?",
    "What did you decide to get?",
    "What did you ask for?",
    "What did you pick out?",
    "What did you enjoy for dinner?",
    "What did you finally choose?",
    "What did you think looked good?",
    "What caught your eye on the menu?",
    "What did you enjoy ordering?",
    "What dish did you go for?",
    "What meal did you pick?",
    "What did you end up having?",
    "What food did you choose?",
    "What did you think sounded good?",
    "What did you feel like eating?",
    "What did you order for the evening?",
    "What was your dinner choice?",
    "What delicious thing did you get?",
    "What did you order to eat?",
    "What was on your order?",
    "What meal did you decide on?",
    "What did you think about ordering?",
    "What tasty thing did you pick?",
    "What did you go for last night?",
    "What was your order like?",
    "What dish did you end up picking?",
    "What was your dinner like?",
    "What did you ultimately choose?",
    "What did you ask for on the menu?",
    "What sounded good to you?",
    "What dish did you select?",
    "What did you finally settle on?",
    "What did you go with for your order?",
    "What option did you choose?",
    "What caught your attention on the menu?"
  ],
  "p2": [
    "How long were you there?",
    "How much time did you spend there?",
    "How long did you hang out there?",
    "How long did you stick around?",
    "What was the duration of your visit?",
    "How much time did you all stay?",
    "For how long were you guys at the place?",
    "How long did you end up being there?",
    "How long did you all hang out?",
    "What’s the total time you spent there?",
    "How long did you chill there?",
    "How long were you hanging out?",
    "How long was your stay there?",
    "What was the length of your time there?",
    "How long did you stay at the venue?",
    "For how long did you guys remain there?",
    "How long were you at the spot?",
    "How long did you spend at that place?",
    "How long did you stick around for?",
    "How long were you guys enjoying yourselves there?",
    "How long did your outing last?",
    "How long did you two end up staying?",
    "What was the time frame of your stay?",
    "How long did you all end up being there?",
    "How long were you at that joint?",
    "How long did you hang out there, by the way?",
    "How long did you spend chilling there?",
    "How long did your time there last?",
    "How long were you there for, then?",
    "How long did your visit take?",
    "How long did you enjoy being there?",
    "How long did it take you to leave?",
    "How long did your time together run?",
    "For how long did you all spend time there?",
    "How long did you end up being at the place?",
    "How long did you linger there?",
    "How long were you at that location?",
    "How long did you stay out for?",
    "What was the length of your stay there, anyway?",
    "How long did you two decide to stay?",
    "How long did you spend there, if you don’t mind me asking?",
    "How long were you out for?",
    "How long was your time there?",
    "How long did you remain at the place?",
    "How long did you guys spend there?",
    "How long did you end up hanging out there?",
    "How long was your time at the venue?",
    "How long were you all hanging out?",
    "How long did you stay there last night?",
    "How long did you treat yourself to being there?",
    "How long did you spend having fun?",
    "How long did you all stay at that place?",
    "How long was your outing, exactly?",
    "How long did it take for you to leave?",
    "How long did you two manage to stay?",
    "How long did you enjoy your time there?",
    "How long did you spend there in total?"
  ],
  "p3": [
    "Absolutely, I understand—it took quite a while. Did anything else catch your attention?",
    "For sure, I see that—it was a lengthy wait. Was there something else that impressed you?",
    "I see what you mean—it was a bit of a wait. Was there anything else memorable for you?",
    "I totally get it—it was a slow wait. Did anything else strike you?",
    "I understand what you're saying—it felt like a long wait. Was there anything else that grabbed your notice?",
    "Yeah, I get it—it was definitely a wait. Did anything else stand out for you?",
    "I see your point—it took some time. Was there anything else you found interesting?",
    "I understand—it was indeed a lengthy wait. Was there anything else you liked?",
    "For sure, I get that—it was quite a wait. Did anything else impress you?",
    "Totally understand—it was a long wait. Was there something else you noticed?",
    "Yeah, I get what you're saying—it was rather slow. Did anything else catch your eye?",
    "I completely understand—it felt like a long wait. Was there anything else you enjoyed?",
    "Absolutely, I see that—it was a bit too long. Did anything else stand out to you?",
    "I hear you—it was a long wait. Was there anything else you found noteworthy?",
    "Definitely, I get it—it took a while. Was there anything else you liked?",
    "I understand your point—it felt like a wait. Was there something else that impressed you?",
    "I gotcha—it was quite a delay. Was there anything else you found appealing?",
    "Yeah, I understand—it was a lengthy wait. Did anything else leave an impression?",
    "I see what you're saying—it was definitely a slow wait. Was there anything else you appreciated?",
    "For sure, I understand—it took longer than expected. Was there anything else that stood out?",
    "Absolutely, I get it—it was kind of drawn out. Did anything else catch your fancy?",
    "I hear that—it was a bit of a wait. Was anything else memorable for you?",
    "Totally get your point—it was a long wait. Was there anything else that stood out?",
    "Yeah, I get what you're saying—it was quite a wait. Did anything else catch your attention?",
    "I totally see your perspective—it was a lengthy wait. Was there anything else you thought about?",
    "I understand, it felt like a long wait. Did anything else resonate with you?",
    "For sure, I get it—it was a slow wait. What else did you think?",
    "Absolutely, I see that—it took longer than usual. Was there something else noteworthy?",
    "I hear you—it was quite the wait. Did anything else stand out to you?",
    "Yeah, I get that—it was indeed a wait. Was there anything else you liked?",
    "I understand your feelings—it was a lengthy wait. What else did you notice?",
    "Totally, I see your point—it took some time. Was there something else you enjoyed?",
    "For sure, I get that—it was a long wait. What else did you think about?",
    "Absolutely, I understand—it was a bit drawn out. Was there anything else interesting?",
    "Yeah, I see what you mean—it was quite a wait. Was anything else memorable?",
    "I totally get you—it felt like a long wait. Any other thoughts?",
    "I understand where you're coming from—it was a long wait. Did anything else catch your eye?",
    "I hear you—it was definitely a slow wait. Anything else you valued?",
    "Totally get that—it was a lengthy wait. Was there something else that stood out?",
    "Yeah, I get your point—it was quite the wait. Did you notice anything else?",
    "I see what you're saying—it took longer. What else did you think?",
    "Absolutely, I get that—it was kind of slow. Did anything else impress you?",
    "For sure, I understand—it was rather lengthy. What else struck you?",
    "I hear you—it was a long wait. Did anything else resonate with you?",
    "Totally understand—it was a bit of a wait. Was anything else on your mind?",
    "I see that—it felt like a wait. Did anything else stand out to you?"
  ],
  "p4": [
    "I completely agree, but if you could alter one aspect of the meal, what would it be?",
    "I'm with you on that, but if you had to change one thing about the meal, what would you pick?",
    "I feel the same, but if there was one thing you could tweak about the meal, what would it be?",
    "I'm on the same page, but if you could modify one part of the meal, what would it be?",
    "I totally see that, but if you could adjust one detail of the meal, what would you choose?",
    "I can relate, but if you were to change one element of the meal, what would it be?",
    "I agree completely, but if you could switch one thing about the meal, what would your choice be?",
    "I see where you're coming from, but if you could refine one thing about the meal, what would it be?",
    "I'm with you, but if you could change one thing regarding the meal, what would it be?",
    "I think you're right, but if you had the chance to change one thing about the meal, what would it be?",
    "I resonate with that, but if you could improve one part of the meal, what would it be?",
    "I get what you mean, but if you could change one aspect of the meal, what would it be?",
    "I totally get your point, but if you had to change one thing about the meal, what would that be?",
    "I can see your point, but if you could revise one thing in the meal, what would you change?",
    "I take your point, but if you had the option to change one thing about the meal, what would it be?",
    "I'm on board with you, but if there was one aspect of the meal you could change, what would it be?",
    "I'm in full agreement, but if you could adjust one part of the meal, what would that be?",
    "I feel you, but if you could change one thing about the meal, what would you change?",
    "I hear you, but if you had to modify one aspect of the meal, what would it be?",
    "I understand where you’re coming from, but if you could alter one element of the meal, what would it be?",
    "I’m totally with you, but if you could switch out one thing about the meal, what would you choose?",
    "I share your thoughts, but if you could change just one thing regarding the meal, what would you do?",
    "I really agree with that, but if you could make one change to the meal, what would it be?",
    "I’m in total agreement, but if there was one thing you could enhance about the meal, what would you pick?",
    "I see your viewpoint, but if you had the chance to change one part of the meal, what would it be?",
    "I agree with you, but if you could change one thing about the meal, what would that be?",
    "I'm aligned with you, but if you could change one thing in the meal, what would it be?",
    "I hear you completely, but if you had the option to alter one thing about the meal, what would it be?",
    "I can relate to that, but if you could change just one aspect of the meal, what would you choose?",
    "I feel you on that, but if one change could be made to the meal, what would that be?",
    "I see your point clearly, but if there’s one thing you could modify about the meal, what would you decide?",
    "I recognize that sentiment, but if you could pick one thing to change about the meal, what would it be?",
    "I can definitely see that, but if you had to change one thing in the meal, what would you do?",
    "I’m in line with that, but if you could change one detail of the meal, what would it be?",
    "I totally get that, but if you had the opportunity to change one aspect of the meal, what would it be?",
    "I completely understand, but if there was one thing you could adjust about the meal, what would that be?",
    "I get what you're saying, but if you had a chance to modify one thing about the meal, what would you choose?",
    "I’m onboard with you there, but if one change could be made to the meal, what would it be?",
    "I totally vibe with that, but if you could change one thing about the meal, what would you go for?",
    "I’m in full alignment with your thoughts, but if there was one thing you could switch about the meal, what would you change?",
    "I see where you’re coming from, but if you could change just one thing in the meal, what would it be?",
    "That makes sense to me, but if there’s one aspect you could change about the meal, what would that be?",
    "I see eye to eye with you, but if you could change one detail of the meal, what would you opt for?",
    "I completely resonate with that, but if you had to choose one thing to change about the meal, what would it be?",
    "I really connect with your thoughts, but if you could alter one thing in the meal, what would that be?",
    "I’m aligned with that perspective, but if there’s one thing you could change in the meal, what would it be?",
    "I’m on the same wavelength, but if you could change just one thing about the meal, what would it be?",
    "I agree wholeheartedly, but if you thought to change one element of the meal, what would your choice be?"
  ],
  "p5": [
    "Oh cool! What was the atmosphere like when they got there?",
    "Great! How was the mood after they showed up?",
    "Awesome! How did things feel when they came in?",
    "Sweet! What was it like once they arrived?",
    "Nice! How was it once they got there?",
    "Cool! How did it feel when they showed up?",
    "That’s great! What was the energy like when they arrived?",
    "Fantastic! How did the vibe change after they got there?",
    "Oh, nice! How was the scene once they joined?",
    "Awesome! How was the feel once they arrived?",
    "That's cool! What was the energy like when they came by?",
    "Oh, neat! How was the atmosphere when they showed up?",
    "How exciting! What was the vibe like when they arrived?",
    "Oh, that’s nice! How did things go once they got there?",
    "Sounds good! What was the mood like after they came?",
    "Great! How did it turn out when they showed up?",
    "Oh sweet! What was the vibe like when they arrived?",
    "Nice! How did the atmosphere feel once they got there?",
    "Cool! What was the scene like after they showed up?",
    "Oh awesome! How was the atmosphere once they arrived?",
    "Great! What was the mood like when they came in?",
    "That’s cool! How did it feel after they showed up?",
    "Oh fun! What was it like once they joined the group?",
    "Fantastic! What was the vibe like when they got there?",
    "Nice! How did it feel once they came by?",
    "Oh, that's exciting! How was it when they arrived?",
    "Great! What was the overall vibe when they showed up?",
    "Awesome! How was the mood once they came in?",
    "Oh, neat! What was it like once they arrived?",
    "Cool! How did the energy feel when they got there?",
    "That’s sweet! What was the atmosphere like after they came?",
    "Oh nice! How did the vibe change once they showed up?",
    "Fantastic! How did the scene feel when they arrived?",
    "Sounds good! What was the mood like after they got there?",
    "Oh, nice! How was the vibe once they came by?",
    "Great! What was the atmosphere like after they got there?",
    "Awesome! How did the energy shift when they joined?",
    "Sweet! How was it when they showed up?",
    "Oh cool! What was it like when they finally arrived?",
    "That’s neat! How was the mood once they got there?",
    "Fantastic! What was the energy like once they arrived?",
    "Oh nice! How did things feel when they came in?",
    "Great! What was the vibe like after they showed up?",
    "Oh fun! What was the atmosphere like when they got there?",
    "Cool! How was it once they joined in?",
    "Oh awesome! How was the scene when they arrived?",
    "Sweet! What did the vibe feel like when they got there?",
    "Nice! How did it change once they showed up?",
    "That’s cool! What was it like once they came?",
    "Oh neat! How was the mood after they arrived?",
    "Great! How was the feel when they showed up?",
    "Awesome! What was the vibe like once they came?",
    "Oh nice! How did things turn out when they arrived?",
    "Sounds fun! What was it like once they got there?",
    "Cool! How was the atmosphere when they came by?"
  ],
  "p6": [
    "What do you think about going for lunch instead of dinner?",
    "How about we have lunch there instead of dinner?",
    "What if we try going for lunch this time instead of dinner?",
    "Should we aim for lunch instead of dinner on our next visit?",
    "What do you say to having lunch rather than dinner this time?",
    "How does lunch sound instead of dinner for our next trip?",
    "What if we switch to lunch instead of dinner when we go back?",
    "Can we consider lunch instead of dinner for our next visit?",
    "How about we eat lunch there instead of going for dinner?",
    "What do you think about lunch instead of dinner next time?",
    "Shall we go for lunch instead of dinner on our next outing?",
    "How about trying lunch this time instead of dinner?",
    "What do you say to meeting for lunch instead of dinner?",
    "Could we do lunch instead of dinner when we revisit?",
    "How about we change it to lunch instead of dinner this time?",
    "What if we opt for lunch over dinner on our next trip?",
    "Should we plan on lunch instead of dinner next week?",
    "How does it sound to do lunch instead of dinner?",
    "What do you think of having lunch instead of dinner next time?",
    "Shall we try having lunch there instead of dinner?",
    "How about we pick lunch instead of dinner this time?",
    "What do you think about switching to lunch for our next visit?",
    "Can we choose lunch instead of dinner for our next outing?",
    "How does going for lunch instead of dinner sound?",
    "What if we go for lunch rather than dinner when we return?",
    "Could we do a lunch date instead of a dinner date this time?",
    "How about revisiting for lunch instead of dinner?",
    "What do you think of going for lunch instead of dinner?",
    "Shall we meet for lunch instead of dinner next week?",
    "How about we opt for lunch over dinner on our next visit?",
    "What if we just stick to lunch this time instead of dinner?",
    "Could we make it lunch instead of dinner for the next try?",
    "How does having lunch instead of dinner work for you?",
    "What if we try out lunch instead of dinner next time?",
    "Shall we go there for lunch this time instead of dinner?",
    "What about switching to lunch instead of dinner?",
    "How does it sound to visit for lunch instead of dinner?",
    "What do you think about a lunch outing instead of dinner?",
    "How about planning a lunch visit instead of dinner?",
    "What if we go out for lunch rather than dinner this time?",
    "Would you be up for lunch instead of dinner on our next trip?",
    "How about we take lunch instead of dinner next week?",
    "Shall we consider lunch instead of dinner for round two?",
    "What do you say to lunch as an alternative to dinner?",
    "Could we possibly do lunch over dinner on our next visit?",
    "How about we schedule lunch instead of dinner this time?",
    "What if we target lunch next time instead of dinner?",
    "Shall we go for lunch rather than dinner next week?",
    "How does lunch instead of dinner sound for our next outing?",
    "What do you think about trying lunch instead of dinner?",
    "Could we switch our visit to lunch instead of dinner next time?",
    "How about having lunch there instead of dinner next week?",
    "What if we plan to go for lunch over dinner this time?"
  ]
} as const;
