/** Frozen M2 intent realizations. One batch. No seed sentence. */
export const FROZEN_INTENT: Readonly<Record<string, readonly string[]>> = {
  "p1": [
    "I hate when that happens. Was the food worth the wait, at least?",
    "That's frustrating! What did you end up ordering?",
    "Slow service can be a bummer. Did you get a chance to talk to your server about it?",
    "What a drag! Did you enjoy the meal despite the wait?",
    "Ugh, nothing worse than slow service. What were you in the mood for?",
    "I know how that feels. Was it a busy night there?",
    "Good to hear you enjoyed the food! What was the highlight of your meal?",
    "That’s too bad about the service! Did you try anything new?",
    "At least the food was good! What was your favorite dish?",
    "I totally get that. Did you see a lot of other tables waiting too?",
    "Slightly annoying! Was it a special occasion for you?",
    "Glad dinner was good! Was there a particular dish that stood out?",
    "That’s a shame. Was it busy, or were they just slow?",
    "I can relate. Did you go with anyone, or just yourself?",
    "It’s tough when the service lags. Did they at least check on you often?",
    "Glad to hear you enjoyed it! What kind of cuisine was it?",
    "That can be such a downer. Did they have a lot of options on the menu?",
    "Sounds like it could have been better. Who did you go with?",
    "It’s great that the food was good! How was the atmosphere?",
    "That's rough! What did you think of the place overall?",
    "Seems like a mixed bag. Did you have dessert, too?",
    "Oh man, that’s frustrating! Did the slow service ruin the vibe?",
    "That’s the worst! How was the atmosphere otherwise?",
    "Good to hear you liked the food! What made the service slow?",
    "I feel you, that's a drag. Did they offer anything to make up for it?",
    "At least the meal was nice! What was the restaurant like?",
    "Slow service can ruin a night. Did you get any appetizers?",
    "Glad it was decent overall! What would you order again?",
    "That’s annoying for sure. Did you give them feedback?",
    "Happy to hear the food was good! How was the drink selection?",
    "It’s good that dinner was enjoyable. Did you have a reservation?",
    "That can be a killer! Did the ambiance help make up for it?",
    "I’m glad you liked your food! Would you go back, though?",
    "That sounds like a mixed experience! What was the best part of the evening?",
    "Slow service can really test your patience. Did that affect your mood?",
    "I get that! What's your favorite type of cuisine when going out?",
    "So it wasn’t perfect? Were there any standout moments?",
    "That’s a bit disappointing. Do you often visit that restaurant?",
    "Glad the food was good! Do you usually go to restaurants like that?",
    "That’s frustrating indeed! How did you find out about the place?",
    "I totally understand. Did you feel like the wait was worth it?",
    "Nice that you enjoyed the meal! What do you like most about dining out?",
    "It is frustrating. Did the server at least seem friendly?",
    "Good to know the food was nice! How did you hear about the restaurant?",
    "That’s not ideal! Were you in a rush, or did you have time to spare?",
    "Glad to hear dinner was tasty! What would you rate it overall?",
    "It can be such a drag when that happens. Did you try their famous dish?",
    "I’m glad the food made up for it! How was the ambiance of the place?",
    "That’s a bummer about service. What’s your go-to dish when you’re out?",
    "Glad the meal itself was good! Did you have any good conversations?",
    "Definitely annoying! Did you catch up on anything while you waited?",
    "I get how that can be! What’s your favorite spot for dinner?"
  ],
  "p2": [
    "So, how long did you guys end up staying there?",
    "Did you hang around for a while, or did you leave pretty quickly?",
    "What time did you finally decide to call it a night?",
    "Did you stick around long enough to get some good food?",
    "I’m curious, how late were you there?",
    "Did you stay for a couple of hours, or was it more of a quick visit?",
    "How long were you two at the bar?",
    "Did you enjoy the atmosphere for a while, or was it too crowded?",
    "So, did you end up making a night of it?",
    "I wonder if you all stayed long to soak in the vibe.",
    "How much time did you spend there before heading home?",
    "Did you guys hang out for a while, or was it a speedy trip?",
    "Did you get a chance to relax there, or did it feel rushed?",
    "How late did you end up being out?",
    "So, was it a quick visit, or did you find time to chill?",
    "Did you manage to enjoy yourselves for a bit, or did you leave early?",
    "How long did you all end up staying in that crowd?",
    "Did you stay long enough to try a few drinks?",
    "I assume you were there for a few hours with the crowd?",
    "What was the vibe like? Were you there long?",
    "Did the busy atmosphere keep you all for a while?",
    "Did you linger there, or was it more of a quick drink?",
    "How long before you called it a night?",
    "Did the packed place keep you both engaged for long?",
    "Were you out long enough to enjoy a few rounds?",
    "Did you get to stay and enjoy the scene, or was it brief?",
    "So, how late did the night go for you both?",
    "Did you hang out long enough to catch up?",
    "How long did you both stick around with all those people?",
    "Did you stay long enough to share some good laughs?",
    "Was it a late night out, or did you head home early?",
    "Did you find time to enjoy the night or just pop in?",
    "Did you stay for a while or just make a quick stop?",
    "How long did you both enjoy the lively atmosphere?",
    "Did you end up staying until it thinned out a bit?",
    "I hope you two got a decent amount of time there!",
    "Did you stay long enough to have some fun before heading out?",
    "How many hours were you in that packed place?",
    "Did you both get to enjoy the night for a while?",
    "So, was it a brief stop or did you hang out longer?",
    "How long did you both manage to stay in the crowd?",
    "Were you there long enough to dance or just for drinks?",
    "Did you soak it all in for a bit, or was it a short trip?",
    "Did you find yourselves there for a while, or was it a quick outing?",
    "Did you stay long enough to get caught up in the atmosphere?",
    "So did you end up exchanging stories for a few hours?",
    "How late did you all chat before heading home?",
    "Did you both make the most of it and stay a bit longer?",
    "Did the crowd keep you there for longer than planned?",
    "How long did you both linger before saying goodbye?",
    "Did it turn into a longer night than you expected?",
    "Did you spend a good chunk of the night there together?",
    "So, how much time did you manage to carve out for yourselves?",
    "Did the place keep you both entertained for a while?",
    "Did you get to catch up and hang out for a bit?",
    "How long did you enjoy the vibe before leaving?"
  ],
  "p3": [
    "I totally get that. Was there anything else about the meal that you really liked?",
    "That must have been frustrating. Did anything else catch your attention?",
    "I understand that waiting can be a bummer. What else stood out to you besides the wait?",
    "I can sympathize with the delay. Was there something specific you enjoyed from the menu?",
    "Yeah, it can be tough to wait. Did any particular dish impress you?",
    "I hear you on the wait. Was there something else that made the meal memorable for you?",
    "Waiting can be such a drag. Did you have a favorite part of the meal, though?",
    "I feel you on that wait. Anything else about the dinner that you thought was worth mentioning?",
    "It’s always a bit annoying to wait, isn’t it? What was your favorite dish of the night?",
    "Totally understand. Was there a particular flavor or dish that made the meal enjoyable?",
    "I can imagine the wait being a bit annoying. What was the highlight of the meal for you?",
    "Yeah, delays can be unwelcome. What did you think of the overall atmosphere, though?",
    "I know how it is with the waiting. Did you have a standout dish?",
    "I sympathize with the wait; it can be so long. Was there anything you really loved?",
    "I get that! Was there anything else about the meal that made it special, even with the wait?",
    "That’s true, waiting is never fun. What did you think about the service otherwise?",
    "That makes sense. Aside from the wait, was there a dish that you thought was particularly good?",
    "Waiting can ruin the mood a bit. Did you have a favorite appetizer or dessert?",
    "I can relate. How did you feel about the drinks they served?",
    "I hear you on that. Was there a certain dish that exceeded your expectations?",
    "Waiting can really test patience. What was your impression of the main course?",
    "Yeah, that’s a hassle. Was the ambiance or vibe nice, at least?",
    "I understand completely. Did anything top your list as the best part of the meal?",
    "That’s definitely a downside. Did any flavors stick with you?",
    "The wait can definitely overshadow things. Was there anything that stood out for you, food-wise?",
    "I get why that would be frustrating. Was there a dish you would recommend to others?",
    "I totally sympathize with you. What did the dessert look like to you?",
    "It must have felt long. Aside from the wait, how did you feel about the flavors?",
    "Waiting isn't fun at all. Did anything surprise you on the menu?",
    "Yeah, I can see how that could be annoying. Was there any dish that surprised you?",
    "Waiting always puts a damper on things. What did you think of the presentation, at least?",
    "True, waiting can be tough. How did you feel about the portion sizes?",
    "That seems frustrating. Was there a certain flavor that stood out to you in the dishes?",
    "I hear you. Were there any dishes you would definitely want to order again?",
    "I can relate to that feeling. What did you think about the chef's specials?",
    "I totally understand. Did the wait affect your experience of the meal overall?",
    "That’s a valid point. Was there anything on the appetizer menu you really enjoyed?",
    "Ugh, waiting can be a hassle. What stood out about the atmosphere of the place?",
    "Yeah, it can definitely get on your nerves. Did you find anything particularly unique on the menu?",
    "That’s understandable. Was there a drink you thought paired really well with the food?",
    "I can see how that would be a letdown. Did any of the dishes surprise you with their flavors?",
    "Totally get it. What did you think of the overall presentation of the food?",
    "I hear you on the wait. Was there a dish that you felt was particularly creative?",
    "I can understand your frustration. Were there any standout flavors in the dishes?",
    "Yeah, waiting can be a pain. Was there something you’d want to try if you went back?",
    "That’s a good point. Did you get to try anything new that you liked?",
    "Totally agree about the wait. What aspect of the meal would you say impressed you the most?",
    "I get that waiting can be a drag. Did any of the flavors resonate with you?",
    "I completely understand. Was there an appetizer that won you over?",
    "Waiting can definitely be a buzzkill. Did you feel the menu was varied enough?",
    "I totally sympathize with the wait. Was there anything about the meal that made it worth it for you?"
  ],
  "p4": [
    "I totally get that! If you could change one thing about the night, what would it be?",
    "That makes sense! What do you think could have made the evening even better?",
    "I’m glad to hear that! If you had the chance to redo something, what would it be?",
    "I feel the same way! What do you think would have been the best fix for the situation?",
    "It’s great to hear you enjoyed dessert! Do you think something else could have improved the night?",
    "Glad to hear it was mostly worth it! Is there anything that would have made it perfect?",
    "It's nice when dessert can work some magic! If you could adjust one part of the night, what would it be?",
    "I agree, dessert can really turn things around! What do you think you’d change if you had the chance?",
    "That's awesome! If you could go back and tweak something, what would it be?",
    "I know what you mean! If you could swap out one aspect of the evening, what would it be?",
    "So true! What do you think you’d have done differently if you could?",
    "Glad you had fun! What do you reckon could have been improved?",
    "Dessert makes everything better, right? What would you have wanted to change about the wait?",
    "I hear you! Would you say there’s one thing in particular that could have improved the night?",
    "It sounds like it was a mixed bag! If you could rewrite one part of the evening, what would it be?",
    "I agree, it's nice when dessert saves the day! What aspect would you have changed?",
    "Totally! If you could pick one thing to adjust, what would you go for?",
    "That’s a relief! Were there any parts of the evening you think could have been better?",
    "Dessert is definitely a highlight! Is there something that would’ve made the wait more bearable?",
    "I’m with you! What do you think could’ve enhanced the experience overall?",
    "It's always nice when things turn around! What would be your top change for next time?",
    "It’s good to hear the dessert helped! What would you have preferred to change about the wait?",
    "I can relate! If you were to change one detail about the evening, what would you choose?",
    "Absolutely! Was there one thing that really stood out that you’d want to tweak?",
    "You said it! If you could make one change to the whole experience, what would that be?",
    "Totally understand! If you could adjust one thing, what would you pick?",
    "Glad it was enjoyable! What do you wish had gone differently?",
    "Dessert has its perks for sure! If you could change one thing about the wait, what would it be?",
    "That makes sense! What do you think could have made the evening flow better?",
    "I get it! If you could change one detail from your night, what would it be?",
    "It sounds like there’s room for improvement! What would be your number one change?",
    "That’s great to hear! If you could go back, what would you tweak?",
    "Definitely! What part of the evening do you think needed a change?",
    "I totally understand. If there was anything you could redo, what would it be?",
    "I can see why you’d feel that way! What do you think could have made it a smoother night?",
    "Dessert is a game changer! What would you have liked to see done differently?",
    "I can definitely see that! Is there one moment you’d wish to change if you could?",
    "Exactly! What do you think could have been done to make the wait worthwhile?",
    "So true! If you had a magic wand, what would you alter about the night?",
    "Great to hear! If you could change just one thing about the event, what would it be?",
    "I totally agree! If you could highlight one change for next time, what would it be?",
    "For sure! What do you think would have made that evening feel more satisfying?",
    "Absolutely! Is there a specific moment you'd want to improve if you could?",
    "I'm glad you enjoyed the dessert! What would you say needed a little tweaking?",
    "I completely relate! What do you think you’d want to change if given the chance?",
    "That’s awesome to hear! If you could change anything from the night, what would it be?",
    "I know that feeling! If you could go back and switch one part, what would it be?",
    "I get that! What change do you think would have made it all worth it?",
    "That’s a great perspective! If you could make one adjustment, what would you choose?",
    "I’m right there with you! If you had the power to change one thing, what would it be?",
    "Sounds like a mixed bag! What would be your top suggestion for a better experience next time?"
  ],
  "p5": [
    "How did the rest of the night pan out?",
    "What happened after they showed up?",
    "So, how was the vibe as the night went on?",
    "Did things get more lively once they arrived?",
    "Did you all have a good time after I left?",
    "What did you guys do for the rest of the evening?",
    "Were there any fun stories or moments that happened later?",
    "How did the energy change once more folks joined?",
    "Did anyone end up telling any wild stories?",
    "Did you all stick around for long after I took off?",
    "What was the highlight of the night after I missed it?",
    "Did everyone enjoy hanging out once the others got there?",
    "Was the party still going strong when they got there?",
    "How did the gathering evolve throughout the night?",
    "After I left, did it get better or was it pretty chill?",
    "What did you and the others get up to after I said goodbye?",
    "Did anyone take charge and lead the fun after I left?",
    "Was there any unexpected drama or excitement as the night progressed?",
    "How did the group dynamic change when those two arrived?",
    "Did you all end up playing games or just chatting?",
    "How'd the conversation flow with the later arrivals?",
    "Was it easy to pick back up the energy once they arrived?",
    "What did the crew end up doing once they showed up?",
    "How'd you feel the rest of the night went compared to when it started?",
    "Did you end up staying longer than you anticipated?",
    "How did it feel having more people around later on?",
    "Did you guys end up grabbing food or something after?",
    "What did you think about the energy in the second half of the night?",
    "Were there any funny moments that stuck with you?",
    "How was it hanging out with the whole crew later on?",
    "Did anyone bring a surprise or something interesting to the mix?",
    "What was the mood like as the crowd grew?",
    "Did you capture any good pictures or videos later in the night?",
    "How did the conversations shift as more people joined?",
    "Did anyone bring up any topics that sparked great discussions?",
    "Was it a relaxed night or did things get a little rowdy?",
    "How did you feel about the turnout after the later arrivals?",
    "Did everyone mix and mingle well when the others came?",
    "What was the best part of the night after I left?",
    "Did you get into any debates or discussions with the new arrivals?",
    "How'd you feel about the overall vibe as the night wrapped up?",
    "Did anyone take the lead on the fun once more people joined?",
    "Was there a big change in the energy once they got there?",
    "How did the late-night crew contribute to the overall experience?",
    "What were some of the highlights from the second half of the night?",
    "Did the conversations flow differently after they arrived?",
    "Was it a more fun crowd with everyone there later on?",
    "Did you end up bonding with anyone new after I left?",
    "What did you think of the dynamic as the night went on?",
    "Did the laughter and stories just keep coming?",
    "Was it a memorable night overall?",
    "Did everyone get along well?",
    "Did you catch up with anyone you hadn't seen in a while?",
    "What was the funniest moment from the rest of the night?"
  ],
  "p6": [
    "How about we aim for a lunch instead? That way we can avoid the wait.",
    "What if we try it for dinner on a weekday? It might be less crowded then.",
    "I totally get that! Maybe we can pick a different spot this time. Any suggestions?",
    "If you're up for it, we could check out that new Italian place next week.",
    "What do you think about brunch instead? I hear their breakfast menu is fantastic.",
    "I understand! Should we look into another restaurant for next week?",
    "I get it! What about looking at some other options, like that taco place you love?",
    "Maybe we can go early in the evening next time? I’d love to avoid the crowds!",
    "I’m good with that! Do you have a different place in mind that we could try?",
    "How about we do a takeout night next week instead? That might be nice to mix it up.",
    "I hear that new sushi spot is good. Wanna check that out next week?",
    "If you're not feeling that place, should we explore some nearby cafes instead?",
    "I get where you're coming from. Would you prefer to try something totally new next week?",
    "What do you say we scout out a food truck instead? They usually have shorter lines!",
    "If you're not keen on that place, let me know what you're in the mood for!",
    "How about we skip that restaurant for now and pick a different cuisine?",
    "Do you want to look for a hidden gem or something fun next week?",
    "Maybe we could find a spot with reservations to save us the wait?",
    "Would you be interested in exploring that new burger place that just opened?",
    "Let’s keep it casual! How about grabbing pizza from somewhere else?",
    "Should we do a picnic next week instead? That could be fun!",
    "If you want, we can do a little food tour around town.",
    "How about we try to find a spot with outdoor seating? It could make the wait more enjoyable!",
    "What do you think about hitting up that diner we used to go to?",
    "If you're thinking of something different, I'm all ears for ideas!",
    "Totally fair! We could also try a food festival if anything’s happening next week.",
    "How do you feel about a cozy café for some coffee and dessert instead?",
    "If you'd prefer, we can simply explore the food trucks. They’re usually quick!",
    "What about taking a look at that new Mediterranean place? It could be a nice change!",
    "I’m fine with that! Maybe we could also find a food stall and make it a little adventure.",
    "Do you think we could find a local brewery that serves food? That might be a fun option.",
    "I get that! Should we try a steakhouse that takes reservations instead?",
    "If you're in the mood, we could hit up that dim sum restaurant that's had great reviews.",
    "How would you feel about sharing a dinner and trying multiple tapas next time?",
    "What if we just decided to go out for dessert instead? That could be easier!",
    "We could also look for a place with a happy hour deal. What do you think?",
    "Maybe we should explore some food apps to find something less popular?",
    "If you're interested, we could try a food delivery service instead and just stay in.",
    "What about hitting up a food festival this weekend? That could be a fun way to explore!",
    "Should we take a drive to that other neighborhood? I've heard there's a great eatery over there.",
    "How would you feel about a quick bite at a fast-casual place next week?",
    "What say you to trying that Mexican spot downtown that just got good reviews?",
    "We could do a little research together this week to find another spot we both like.",
    "How about a themed dinner night at home? We could cook together and make it fun!",
    "Do you think we should keep it simple and just grab sandwiches or something?",
    "What would you say to a little food truck hop around the city?",
    "If you're up for it, we can explore a new dessert place for a sweet treat!",
    "How does a casual café sound instead? I could go for a relaxed atmosphere.",
    "What do you think about trying a new brunch spot? I’ve heard they have great mimosas!",
    "If you want to take a break from all that, we could just grab coffee and a pastry.",
    "Would you prefer checking out a diner or a trendy café for something different?",
    "How about we scout out a new ramen place? They usually have a shorter wait time.",
    "I'm all for changing it up! Should we try a Brazilian steakhouse?",
    "What do you think of going for burgers at that place with great reviews?"
  ]
} as const;
