/** Frozen M3 independent draws. One batch. Do not regenerate after scoring. */
export const FROZEN_DRAWS: Readonly<Record<string, readonly string[]>> = {
  "p1": [
    "Oh, I hate when that happens! Did you at least enjoy the food? What did you end up ordering?",
    "Yeah, that's always a bit frustrating. What did you end up ordering?",
    "I get that. That can be a bit frustrating. What did you end up ordering?",
    "Yeah, I hate when that happens. Did you at least enjoy the food?",
    "That’s good to hear! Did you try anything new on the menu, or did you stick with your usual favorites?",
    "Yeah, I totally get that! Sometimes it can be a bit frustrating waiting for your food. What did you end up ordering?",
    "That’s good to hear! What did you end up ordering?",
    "Yeah, slow service can be a bummer. What did you end up ordering?",
    "Oh, that’s good to hear, at least! What did you end up ordering?",
    "Yeah, I hate it when that happens. What did you end up ordering?",
    "That’s good to hear, but slow service can be so frustrating! Did you try anything new on the menu?",
    "Yeah, I can understand how that can be frustrating. Did you end up ordering anything special?",
    "I hate when that happens! Did you at least enjoy the food? What did you end up ordering?",
    "That's good to hear! What did you end up ordering?",
    "I get that; slow service can be frustrating. What did you end up ordering?",
    "I hate when that happens. Did you try anything special on the menu?",
    "That can be frustrating! Did you end up ordering something special, or just your usual go-to?",
    "Oh, that’s too bad about the service! Did the food make up for it at least? What did you end up ordering?",
    "That’s a bummer about the service! What did you end up ordering?",
    "Yeah, I totally get that. Sometimes it can be frustrating when you're hungry and waiting. What did you end up ordering?",
    "Yeah, I've noticed that can happen sometimes. What did you end up ordering?",
    "That’s good to hear! Was there anything in particular that you ordered that you really enjoyed?",
    "Yeah, I hate when that happens! What did you end up ordering?",
    "That’s good to hear, but I hate when the service drags on. Did you end up trying anything new on the menu?",
    "I get that; sometimes it can really drag on. What did you end up ordering?",
    "Oh, that’s always a bummer when the service lags. What did you end up ordering?",
    "That sounds like a nice evening despite the wait! What did you end up ordering?",
    "That’s good to hear! What did you end up ordering?",
    "Yeah, I hate it when that happens. What did you end up ordering?",
    "Yeah, I hate when that happens. Did you at least have a good meal? What did you end up ordering?",
    "Yeah, that can be frustrating. What did you end up ordering?",
    "That’s good to hear! Slow service can be a bit frustrating, though. What did you end up ordering?",
    "Oh yeah, I hate when that happens. Did you at least enjoy the food?",
    "That’s good to hear, despite the slow service. What did you end up ordering?",
    "Oh, I hate when that happens! Was the food worth the wait at least? What did you end up ordering?",
    "Oh, I hate when that happens! Did you at least get to try something new or was it your usual order?",
    "Yeah, I get that. What did you end up ordering?",
    "Yeah, slow service can be frustrating! Did you order anything special?",
    "Oh, I hate when that happens! Did you at least enjoy the food? What did you end up ordering?",
    "That’s good to hear! It’s a bummer when the service drags, though. What did you end up ordering?",
    "Yeah, I hate when that happens. Did you at least enjoy the food?",
    "I get that; it can be frustrating when you’re waiting for your food. Did you at least enjoy what you ordered?",
    "Oh, that’s good to hear! Slow service can be a bit frustrating, though. What did you end up ordering?",
    "Yeah, that can be frustrating. What did you end up ordering?",
    "Yeah, I get that. Sometimes it can really drag things out. What did you end up ordering?",
    "That's good to hear! What did you end up ordering?",
    "Oh, that’s always a bit frustrating! Did you have anything special on the menu?",
    "Yeah, slow service can be a bummer. What did you end up ordering?",
    "Yeah, I hate when that happens. What did you end up ordering?",
    "That’s good to hear, but I hate it when the service drags. Did you at least get to try something new on the menu?"
  ],
  "p2": [
    "That sounds fun! Did you guys stay long, or was it too crowded to enjoy?",
    "That sounds like a good time! Did you guys end up staying long, or was it too crowded to enjoy?",
    "Oh wow, that sounds lively! How long did you guys end up staying there?",
    "That sounds like fun! Did you stay there long, or was it too crowded to enjoy?",
    "Oh really? Did you end up staying long then, or did you leave pretty quickly because of the crowd?",
    "Oh nice! Did you stay long, or was it too crowded to enjoy?",
    "Oh nice! Did you end up staying long despite the crowd? It must have been fun if you did!",
    "That sounds like a lot of fun! Did you guys end up staying long, or was it too crowded to really enjoy it?",
    "Oh nice! Did you guys stay there long, or was it too crowded to enjoy?",
    "Oh really? That sounds fun! How long did you end up staying there?",
    "Oh nice! Did you end up staying long then, or was it too crowded to enjoy?",
    "Oh nice! Did you guys stay there long, or was it just too crowded to enjoy?",
    "Oh wow, sounds like a fun time! Did you end up staying long, or was it too crowded to enjoy?",
    "Wow, that sounds lively! Did you guys end up staying long, or was it too crowded to enjoy?",
    "Oh wow, sounds like a fun time! Did you guys end up staying long, or was it too crowded to really enjoy it?",
    "Oh wow, that sounds like fun! Did you guys end up staying long, or was it just too crowded to enjoy?",
    "Oh, nice! Did you end up staying long, or was it too crowded to enjoy?",
    "Oh nice! Did you stay long then, or was it too crowded to enjoy?",
    "Oh nice! Did you end up staying long, or was it too crowded to relax?",
    "Oh nice! Did you guys end up staying long, or was it too crowded to enjoy?",
    "Oh, nice! Did you guys end up staying long or just grabbing a quick drink? It must have been quite the vibe with so many people there.",
    "Oh nice! Did you guys stay for long, or was it too crowded to relax?",
    "Wow, that sounds lively! Did you guys end up staying long, or did you move on to another spot?",
    "That sounds fun! Did you guys stay there for long, or was it too crowded to enjoy?",
    "That sounds fun! How long did you guys end up staying there?",
    "Oh, nice! Did you end up staying long, or was it too crowded for that?",
    "Wow, sounds like it was lively! Did you guys end up staying long, or did you leave pretty quickly because of the crowd?",
    "That sounds like fun! Did you end up staying long, or was it too crowded to enjoy?",
    "Oh, nice! Did you guys end up staying for a while, or was it just too crowded?",
    "That's awesome! Did you guys end up staying long despite the crowd?",
    "Oh, nice! Did you guys end up staying long, or was it too crazy to enjoy?",
    "Oh, nice! Did you guys stay long, or was it too crowded to enjoy?",
    "That sounds fun! Did you end up staying long, or was it too crowded to find a good spot?",
    "That sounds like fun! Did you end up staying for a long time, or was it too crowded to enjoy?",
    "Oh wow, sounds like a lively night! Did you guys stay long, or was it too crowded to find a good spot?",
    "Oh really? Did you guys stay long then, or was it too crowded to enjoy?",
    "Oh wow, sounds like a lively evening! Did you end up staying there long, or did you guys decide to head somewhere else after?",
    "Oh nice! Did you guys end up staying long then? It must have been hard to find a spot with all those people around.",
    "Wow, that sounds lively! Did you end up staying long, or was it too crowded to enjoy?",
    "Oh, nice! Did you stay there long, or did you decide to move on to another place after a while?",
    "Wow, that sounds like fun! Did you guys end up staying long, or was it too crowded to enjoy?",
    "Oh, nice! Did you guys stay long then? It must have been fun to be out in that kind of atmosphere.",
    "Wow, sounds like it was a lively atmosphere! How long did you guys end up staying there?",
    "Oh nice! Did you guys stay long, or was it too crowded to enjoy?",
    "Oh nice! Did you end up staying there long, or did you decide to move on to a quieter spot?",
    "Wow, that sounds lively! Did you guys stay long, or was it too crazy to enjoy?",
    "Wow, sounds like it was quite the scene! Did you guys stay for a while, or did you end up heading home early?",
    "Oh nice! Did you guys stay for long, or was it so crowded that you decided to leave early?",
    "Wow, it sounds like a fun time! Did you guys end up staying long, or was it too crowded to really enjoy it?",
    "Oh nice! Did you guys end up staying there long, or did you try to find somewhere else to chill?"
  ],
  "p3": [
    "I totally get that; waiting can be so frustrating. Was there anything else that stood out to you, maybe the ambiance or the service?",
    "I totally get that, waiting can be such a drag! Was there anything else that stood out to you, like a particular dish or maybe the ambiance?",
    "I totally get that; waiting can be frustrating, especially when you're hungry! Was there anything else about the meal that stood out to you?",
    "I totally get that; waiting can be such a bummer. Was there anything else that stood out to you, like the atmosphere or a particular dish that you enjoyed?",
    "I totally get that; waiting can be such a drag. But was there anything else about the meal that stood out to you?",
    "I totally get that; waiting can be so frustrating. Was there anything else that stood out to you, maybe a particular dish you really liked?",
    "I totally get that, waiting can be such a drag. Did anything else stand out to you, like the ambiance or a particular dish you liked?",
    "Yeah, I totally get that. Waiting can really kill the mood sometimes. Was there anything else that stood out to you, either good or bad?",
    "I totally get that; waiting can be such a drag. Was there anything else about the evening that stood out to you?",
    "Yeah, I know the wait can be a bit frustrating. Besides that, was there anything else that stood out to you about the meal?",
    "I totally get that; waiting can be such a mood killer. Besides the wait, was there anything else that stood out to you?",
    "Yeah, I totally get that; waiting can be a drag. Was there anything else that stood out to you, like the atmosphere or the service?",
    "I completely understand, waiting can be a bit frustrating. Was there anything else that stood out to you, like the atmosphere or the service?",
    "I totally get that, waiting can be such a drag! Was there anything else that stood out to you, maybe the dessert or the ambiance?",
    "I totally get that; waiting can be a bit frustrating. Was there anything else that stood out to you, maybe the ambiance or the service?",
    "I totally get that; waiting can be a bit frustrating. Was there anything else about the evening that stood out to you?",
    "I totally understand that waiting can be a bit frustrating. Besides the wait, was there anything else that stood out to you?",
    "I totally get that, waiting can be such a drag. Was there anything else that stood out to you, maybe a dish you really liked?",
    "I totally get that; waiting can be so frustrating. Was there anything else about the meal that stood out to you, like a dish you really enjoyed?",
    "I totally get that; waiting can be a drag. Was there anything else that stood out to you, maybe a dish you particularly liked or something unexpected?",
    "I totally get that, waiting can be such a drag! Was there anything else that stood out for you, maybe a particular dish you really enjoyed?",
    "I totally get that; waiting can really put a damper on things. Was there anything else that stood out to you, like a specific dish or maybe the service?",
    "I totally get that, waiting can be such a drag. Was there anything else that stood out to you, like the atmosphere or the service?",
    "I totally get that; waiting can be a bit frustrating. Was there anything else that stood out to you about the meal? Maybe a dish you really liked?",
    "I totally get that, waiting can be a bit of a drag. Did you have a favorite dish, or was there anything that surprised you about the meal?",
    "I totally get that; waiting can be pretty frustrating. Was there anything else that stood out to you, maybe the ambiance or the service?",
    "I totally get that; waiting can be such a drag. Was there anything else about the evening that stood out to you?",
    "I totally get that; waiting can be a bit frustrating. Was there anything else that stood out for you, like the dessert or the atmosphere?",
    "I totally get that, waiting can be so frustrating. Did anything else stand out to you, like the atmosphere or the service?",
    "I totally get that, waiting can be such a drag. Was there anything else that stood out to you, like the atmosphere or the service?",
    "I totally get that; waiting can definitely take away from the experience. Was there anything else that stood out to you, like the ambiance or a specific dish that you really enjoyed?",
    "I totally get that; waiting can be such a drag. Was there anything else that stood out to you, maybe a dish you really liked?",
    "I totally get that; waiting can be a drag. Was there anything else about the evening that stood out to you?",
    "I totally understand, waiting can be such a drag. Did anything else stand out for you, maybe a dish you particularly enjoyed?",
    "I totally get that; waiting can be a drag. Was there anything on the menu that really stood out to you, though?",
    "Yeah, I get that waiting can be frustrating. Was there anything else that stood out to you, like the atmosphere or the service?",
    "Yeah, I totally get that. Waiting can be a real drag. Was there anything else that stood out to you, like the service or the atmosphere?",
    "I totally get that; waiting can be such a drag. Was there anything else that stood out to you, like the ambiance or the service?",
    "I totally get that waiting can be a bit frustrating. Besides the wait, was there anything else that stood out to you about the meal?",
    "I totally get that, waiting can be such a drag. Was there anything else that stood out to you, like the ambiance or the service?",
    "I totally get that; waiting can be such a drag. Was there anything else that stood out to you, maybe the ambiance or the service?",
    "I totally get that; waiting can really take away from the experience. Was there anything else that stood out for you, like the ambiance or a particular dish you liked?",
    "I totally get that; waiting can be a bit frustrating. Aside from the wait, was there anything else that stood out to you, like a dish you really enjoyed?",
    "I totally get that; waiting can be so frustrating. Was there anything else that stood out to you, like the atmosphere or any particular dish you enjoyed?",
    "I totally get that; waiting can be a bit frustrating. Besides the wait, was there anything else that really stood out to you?",
    "Yeah, I totally get that waiting can be a bit frustrating. Was there anything else that stood out to you, like the ambiance or a particular dish you enjoyed?",
    "Yeah, I totally get that waiting can be frustrating. Was there anything else that stood out for you, like the dessert or the ambiance?",
    "I totally get that; waiting can be really frustrating. Was there anything else that stood out to you about the meal?",
    "I can totally understand that waiting can be really frustrating. Was there anything else about the night that stood out to you?",
    "I totally understand that waiting can be frustrating. Was there anything else about the meal or the atmosphere that stood out to you?"
  ],
  "p4": [
    "I totally get that! The dessert really can be the highlight sometimes. If you could change one thing about the evening, what would it be?",
    "I’m glad to hear that! The dessert can really make a difference sometimes. If you could change one thing about the evening, what would it be?",
    "I’m glad to hear that! Desserts can really be the highlight sometimes. If you could change anything about the evening, what would it be?",
    "I’m glad to hear it was mostly worth it! If you could change one thing about the evening, what would it be?",
    "I totally get that! The wait can be frustrating, but when dessert hits the spot, it helps. If you could change anything about the evening, what would it be?",
    "I'm glad to hear the dessert was a highlight! If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert does have a way of making everything feel a bit better. Is there anything you would change about the experience to make it even better next time?",
    "I'm glad to hear the dessert helped! If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can definitely be a game changer. If you could change anything about the evening, what would it be?",
    "I'm glad to hear it was worth it! If you could change one thing about the evening, what would it be?",
    "I’m glad to hear that! The dessert really can be a game changer. If you could have changed one thing about the evening, what would it have been?",
    "I get that! The dessert can really be a game-changer. If you could change anything about the whole experience, what would it be?",
    "I’m glad to hear the dessert was a highlight! If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can really make a difference. If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can be a game-changer sometimes. If you could change anything about the evening, what would it be?",
    "I’m glad to hear the dessert was a highlight! If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can really save the day sometimes. If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can really save the day. If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert was definitely a highlight. If you could change one thing about the evening, what would it be?",
    "I'm glad to hear that! What do you think you would change if you could? Maybe the timing or the service?",
    "I’m glad to hear that! What do you think would have made it even better? Would you change anything about the experience?",
    "I totally get that! The dessert can really make a difference sometimes. If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can really turn things around. If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can really save the day sometimes. If you could change one thing about the evening, what would it be?",
    "I’m glad to hear that! The dessert really can be a game changer. If you could change anything about the evening, what would it be?",
    "I totally get that! The dessert can definitely save a night. If you could change one thing about the whole experience, what would it be?",
    "I totally get that! The dessert can really make a difference. If you could change one thing about the evening, what would it be?",
    "I totally get that! Dessert can be a game changer. If you could change one thing about the evening, what would it be?",
    "I'm glad to hear that! The dessert can really make or break the experience sometimes. If you could change one thing about the evening, what would it be?",
    "I totally get that! The dessert can really steal the show. If you could change one thing about the whole experience, what would it be?",
    "I’m glad to hear that! What do you think you would have changed to make it even better?",
    "I'm glad to hear the dessert was a highlight! If you could change anything about the evening, what would it be?",
    "I’m glad to hear that! The dessert can really be a game changer. What do you think you would change about the experience to make it even better?",
    "I'm glad to hear that! The dessert really can make a difference. If you could change anything about the evening, what would it be?",
    "I'm glad to hear that! What do you think could have made the evening even better?",
    "I'm glad to hear that! The dessert really can be a game-changer. If you could change one thing about the evening, what would it be?",
    "I'm glad to hear that! The dessert can really make or break the evening sometimes. If you could change one thing about the whole experience, what would it be?",
    "I’m glad to hear that! The dessert can really make a difference. If you could change one thing about the evening, what would it be?",
    "I’m glad to hear that! What do you think they could have done differently to make the experience even better?",
    "I’m glad to hear it was mostly worth it! If you could change anything about the evening, what would it be?",
    "I totally get that! The dessert can really save the night sometimes. If you could change anything about the evening, what would it be?",
    "I'm glad to hear that! The dessert can really be a game-changer sometimes. If you could change anything about the evening to make it even better, what would it be?",
    "I'm glad to hear the dessert was a highlight! If you could change one thing about the whole experience, what would it be?",
    "I’m glad to hear that! What do you think you would change to make the whole experience better?",
    "I'm glad to hear that! The dessert can really make a difference. If you could change one thing about the evening, what would it be?",
    "I'm glad to hear the dessert was a highlight! If you could change anything about the evening, what would it be?",
    "I’m glad to hear that! What do you think would have made the evening even better?",
    "I'm glad to hear that! The dessert can really make a difference sometimes. If you could change anything about the evening, what would it be?",
    "I totally get that! The dessert can really save the day sometimes. If you could change one thing about the whole experience, what would it be?",
    "I totally get that! The dessert can really save the day sometimes. If you could change one thing about the whole experience, what would it be?"
  ],
  "p5": [
    "Oh, nice! How did the rest of the night go after they arrived? Did you all end up having a good time?",
    "Oh, nice! How did the rest of the night go, then? Did you all end up having a good time?",
    "Oh nice! How did the rest of the night go? Did everyone have a good time?",
    "Oh, that’s cool! How did the rest of the night go after we left? Did you guys end up staying out late?",
    "Oh, nice! How did the rest of the night go after that? Did you guys end up having a good time?",
    "Oh, nice! How did the rest of the night go? Were there any highlights or funny moments?",
    "Oh nice! How did the rest of the night go after that? Did you all have a good time?",
    "Oh, nice! How did the rest of the night go? Did you all have a good time?",
    "Oh, nice! How did the rest of the night go after that? Did everyone have a good time?",
    "Oh, cool! How did the rest of the night go after that? Did you all have a good time?",
    "Oh, nice! How did the rest of the night go? Was it as fun as it usually is?",
    "Oh, nice! How did the rest of the night go for you all? Did you end up staying long?",
    "Oh, nice! How did the rest of the night go? Was it a good turnout, or did things die down pretty quickly?",
    "Oh, nice! How did the rest of the night go after that? Did you all have a good time?",
    "Oh, nice! How did the rest of the night go? Did you guys end up having a good time?",
    "Oh nice! How did the rest of the night go? Was it fun once more people showed up?",
    "Oh nice! How did the rest of the night go? Did you all have a good time?",
    "Oh nice! How did the rest of the night go? Was it as fun as it sounded?",
    "Oh nice! How did the rest of the night go after they arrived? Did everyone have a good time?",
    "That’s cool! How did the rest of the night go? Did you all end up having a good time?",
    "Oh nice! How did the rest of the night go? Did you all end up having a good time?",
    "Oh nice! How did the rest of the night go? Did you all end up having a good time?",
    "Oh, nice! How did the rest of the night go? Did you all end up staying long?",
    "Oh, nice! How did the rest of the night go after that? Did you guys end up having a good time?",
    "Oh nice! How did the rest of the night go after we left? Did you all have a good time?",
    "Oh, nice! How did the rest of the night go? Did you guys have a good time?",
    "Oh, nice! How did the rest of the night go? Did it get lively once they arrived, or was it more of a chill vibe?",
    "Oh, nice! How did the rest of the night go? Did you all have a good time?",
    "Oh, nice! How did the rest of the night go? Did you all have a good time catching up?",
    "Oh, nice! How did the rest of the night go after that? Did you all end up having a good time?",
    "Oh nice! How did the rest of the night go after they arrived? Did everyone have a good time?",
    "Oh nice! How did the rest of the night go? Did you guys end up having a good time?",
    "That’s cool! How did the rest of the night go? Did everyone have a good time?",
    "Oh, nice! How did the rest of the night go? Was it fun?",
    "Oh, nice! How did the rest of the night go after they arrived? It must have been fun to have more people there.",
    "Oh, nice! How did the rest of the night go? Was it fun to catch up with everyone?",
    "That sounds nice! How did the rest of the night go? Did you all end up having a good time?",
    "Oh, nice! How did the rest of the night go for you all? Was it as fun as it looked from the photos?",
    "Oh, nice! How did the rest of the night go? Did you all have a good time?",
    "Oh, nice! How did the rest of the night go after that? Did you guys end up having a good time?",
    "Oh, nice! How did the rest of the night go? Did you all end up having a good time?",
    "Oh, nice! How did the rest of the night go? Did everyone have a good time?",
    "Oh, nice! How did the rest of the night go after they arrived? Did everyone have a good time?",
    "Oh, nice! How did the rest of the night go after I left? Did you guys end up having a good time?",
    "Oh nice! How did the rest of the night go? Was it a good turnout overall?",
    "Oh nice! How did the rest of the night go after that? Did you guys end up staying long?",
    "Oh, nice! How did the rest of the night go? Did everyone have a good time?",
    "Oh nice! How did the rest of the night go then? Did you all end up having a good time?",
    "Oh, nice! How did the rest of the night go? Did you all end up having a good time?",
    "Oh, nice! How did the rest of the night go after that? Did you all end up doing anything fun?"
  ],
  "p6": [
    "That’s fair! How about we look for a place we can get into a bit quicker? Any particular cuisine you’re in the mood for next time?",
    "That's fair! How about we look for something else this weekend instead? What are you in the mood for?",
    "How about we go for brunch instead? I hear they have a great weekend special, and it might be less crowded. What do you think?",
    "How about we aim for a lunch time instead? That way we can avoid the dinner rush. What kind of food are you in the mood for?",
    "How about we aim for a lunch instead? That way we can avoid the dinner rush. Or is there somewhere else you had in mind?",
    "How about we go for lunch instead? That way we can avoid the dinner rush and hopefully get seated faster. What kind of food are you in the mood for next time?",
    "How about we aim for a lunch instead? That way we can avoid the dinner rush and enjoy the food without the long wait. What are you in the mood for?",
    "How about the weekend instead? We could try for an earlier dinner to avoid the rush. What are you in the mood for?",
    "I totally get that! How about we look at some other spots in the meantime? Any particular type of cuisine you’re in the mood for?",
    "How about we try it for lunch instead? Or do you have a different place in mind that you'd like to check out?",
    "How about we go for lunch instead? We could avoid the dinner rush, and it might be a bit quieter. What are you in the mood for next time?",
    "How about we aim for a weekday evening then? I’ve heard some good things about that new Italian place too, if you’re open to trying something different!",
    "How about we aim for a lunch spot instead? That way we can beat the dinner rush. What kind of food are you in the mood for next time?",
    "I get that! How about we aim for an early dinner next time? Or is there somewhere else you’ve been wanting to try?",
    "How about we aim for a weekend then? Or is there somewhere else you’ve been wanting to try?",
    "I get that! How about we aim for a lunch spot instead? Or is there somewhere else you've been wanting to try?",
    "How about we aim for a lunch next Saturday? That way we can avoid the dinner rush. Or do you have a specific place in mind that you'd like to try?",
    "How about we try it for lunch instead? That way we can skip the dinner rush. What kind of food are you in the mood for next time?",
    "How about we aim for a weekday instead? That way, we might avoid the rush. Any particular cuisine you’re in the mood for next time?",
    "How about we aim for a lunchtime visit instead? That way we can avoid the rush and just enjoy the meal! What are you in the mood for?",
    "How about we check out that new Italian spot instead? I heard their pasta is amazing, and we can go early to avoid the rush! What do you think?",
    "How about we aim for a lunch spot instead? That way we can avoid the dinner rush. Plus, do you have any other places in mind that you’ve been wanting to try?",
    "How about we aim for a lunch instead? I feel like that might cut down on the wait time. What are you in the mood for next time?",
    "How about we aim for a lunch spot instead? It might be a bit quieter and we can avoid the long wait. What kind of cuisine are you in the mood for next time?",
    "How about we aim for a lunch spot instead? It might be less crowded, and we can avoid that long wait. What kind of food are you in the mood for?",
    "That makes sense! How about we aim for a lunch instead? Or is there somewhere else you’d prefer to check out?",
    "How about we aim for the weekend instead? Or is there somewhere else you’ve been wanting to check out?",
    "How about we aim for a lunch instead? That way we can avoid the dinner rush. What kind of food are you in the mood for next time?",
    "How about we check out that new café instead? I’ve heard great things about their brunch menu.",
    "How about we aim for a lunch instead? That way we can skip the rush and really enjoy the meal. What do you think?",
    "How about we aim for a weekday evening instead? That way we might avoid the rush. Do you have any other places in mind that you’ve been wanting to check out?",
    "How about we aim for a lunch instead? It might be less crowded then. Or do you have somewhere else in mind that you’d like to try?",
    "How about we plan for a lunch instead? It might be less crowded, and we can avoid that long wait. What kind of food are you in the mood for next time?",
    "How about we aim for a lunch instead? We could avoid the dinner rush and just enjoy the food without the long wait. What do you think?",
    "How about we go for lunch instead? I feel like that might be less crowded, and we can still enjoy the food without the long wait. What do you think?",
    "How about we aim for a lunch date instead? That way we can skip the dinner rush and really enjoy the meal. What are you in the mood for next time?",
    "How about we try for an earlier time next week? Or is there a different restaurant you’ve been wanting to check out instead?",
    "How about we aim for a weekend lunch instead? That way we can avoid the evening rush. Do you have any other places in mind you'd like to try?",
    "How about we aim for a lunch this time instead of dinner? It might be less crowded then, and we can avoid the long wait. What do you think? Any other places you want to try?",
    "How about we aim for a lunch next weekend instead? It might be less crowded then. What kind of food are you in the mood for?",
    "How about we aim for the weekend then? Or is there a different spot you’ve been wanting to check out?",
    "How about we aim for a weekday evening instead? Or is there a specific type of cuisine you're craving for our next outing?",
    "How about we aim for a lunch outing instead? We could avoid the dinner rush and still enjoy the food without the long wait. What do you think?",
    "How about we aim for a lunch trip instead? That way we can skip the dinner rush and enjoy our meal without the long wait. What kind of cuisine are you in the mood for this time?",
    "How about we aim for a lunch date instead? We could avoid the dinner rush and enjoy the food without the long wait. What do you think?",
    "That makes sense! How about we check out that new sushi place we talked about instead? I’ve heard great things about it, and it’s supposed to have a shorter wait.",
    "How about we aim for an earlier time if we go back? Or is there somewhere else you've been wanting to check out?",
    "How about we aim for a lunch date instead? It might be less crowded, and we can avoid the long wait. What kind of food are you in the mood for next time?",
    "How about we aim for a weekday lunch instead? It might be less crowded then. What kind of food are you in the mood for next time?",
    "How about we aim for a lunch spot instead? I feel like we could avoid the dinner rush that way. What kind of cuisine are you in the mood for next time?"
  ]
} as const;
