/**
 * Frozen F10 sparse argument. One run. Do not regenerate.
 */
export const FROZEN = {
  "start": "Shall we begin this tiny round now?",
  "argument": "10110110",
  "result": "ARGUMENT",
  "turns": [
    {
      "speaker": "A",
      "intent": "Ask if they still want to go to the market in the morning.",
      "mode": "SKIP",
      "bits": "",
      "next": "SKIP",
      "utterance": "Hey, are we still planning to hit the market in the morning?",
      "c6": 56
    },
    {
      "speaker": "B",
      "intent": "Say the early stall is worth it if they leave before nine.",
      "mode": "SKIP",
      "bits": "",
      "next": "DATA",
      "utterance": "Yeah, definitely! If we leave before nine, we can snag the best deals at the early stalls.",
      "c6": 30
    },
    {
      "speaker": "A",
      "intent": "Ask whether they should pick up bread there or bake later.",
      "mode": "DATA",
      "bits": "10",
      "next": "DATA",
      "utterance": "Should we grab some fresh bread at the market, or do you think we should just bake it later?",
      "c6": 19
    },
    {
      "speaker": "B",
      "intent": "Say last time the loaves were gone by the time they arrived.",
      "mode": "DATA",
      "bits": "11",
      "next": "SKIP",
      "utterance": "I remember last time we got there, all the fresh loaves were sold out by the time we arrived.",
      "c6": 38
    },
    {
      "speaker": "A",
      "intent": "Ask if they need anything else besides tomatoes.",
      "mode": "SKIP",
      "bits": "",
      "next": "DATA",
      "utterance": "Hey, while we're at the market, do you think we should pick up anything else besides tomatoes?",
      "c6": 7
    },
    {
      "speaker": "B",
      "intent": "Mention they still have rice but are out of lemons.",
      "mode": "DATA",
      "bits": "0",
      "next": "DATA",
      "utterance": "I still have some rice at home, but we could really use some lemons.",
      "c6": 0
    },
    {
      "speaker": "A",
      "intent": "Ask whether they want to cook at home or eat nearby after.",
      "mode": "DATA",
      "bits": "11",
      "next": "DATA",
      "utterance": "What do you think about cooking at home with all our fresh finds, or should we go out and eat instead?",
      "c6": 11
    },
    {
      "speaker": "B",
      "intent": "Say cooking at home is fine if the kitchen is not a mess.",
      "mode": "DATA",
      "bits": "0",
      "next": "SKIP",
      "utterance": "As long as the kitchen isn’t a total mess, I’m down for a home-cooked meal.",
      "c6": 45
    }
  ],
  "candidates": [
    [
      "Hey, are we still planning to hit the market in the morning?",
      "Just wanted to check if you’re still up for going to the market tomorrow morning.",
      "So, what do you think about going to the market in the morning? Still interested?",
      "Are we still good for the market trip in the morning?",
      "I was thinking about our market plan for tomorrow—still want to go?",
      "You still thinking about heading to the market in the morning?",
      "Just touching base—are we still on for the market in the morning?",
      "By the way, are we still going to that market tomorrow?",
      "Is the market still on your agenda for morning?",
      "So, are we still set to go to the market in the morning?",
      "Just checking in, are you still game for the market tomorrow morning?",
      "Do you still want to swing by the market in the morning?",
      "Are we still planning to visit the market first thing tomorrow?",
      "Hey, remind me, are we still going to the market in the morning?",
      "I was curious if you’re still up for the market excursion in the morning.",
      "Let me know if you are still interested in hitting up the market tomorrow morning.",
      "Are we still on for the morning at the market?",
      "Thinking about the market tomorrow, do you still want to go?",
      "Hey, just wanted to see if we’re still doing the market in the morning.",
      "You still down for that market trip tomorrow morning?",
      "So, how do you feel about going to the market in the morning?",
      "Are you still excited about checking out the market tomorrow morning?",
      "I hope you're still up for the market visit in the morning!",
      "What do you say about going to the market in the morning? Still want to?",
      "I was just wondering if you're still planning to go to the market tomorrow morning.",
      "Are you still up for a morning jaunt to the market?",
      "Do you still want to check out that market tomorrow morning?",
      "Is that market trip still on for morning?",
      "Are we still thinking about going to the market bright and early?",
      "Let me know if you’re still interested in the market tomorrow morning.",
      "I wanted to ask if you’re still on for the market. Is that still happening?",
      "So, about that market plan—are we still going in the morning?",
      "Are we still planning to go to the market first thing?",
      "Let me know if you’re still keen on hitting the market in the morning.",
      "Just a quick check: still good for the market tomorrow morning?",
      "Hey, are you still thinking about going to the market bright and early?",
      "Do you want to stick to our market plans for the morning?",
      "I was just thinking about the market for tomorrow, are we still going?",
      "Have you changed your mind about the market in the morning?",
      "Still feeling good about heading to the market in the morning?",
      "What’s the verdict on the market tomorrow morning? Are we still in?",
      "Are we still set for that market visit in the morning?",
      "Hey, are we still planning to hit the market early tomorrow?",
      "Just wanted to confirm if you’re still up for the morning market trip.",
      "So, morning market? Thumbs up or down?",
      "Do you still want to do the market run tomorrow morning?",
      "Are we still on track to check out the market in the morning?",
      "Just double-checking—are we still in for the market adventure tomorrow?",
      "What’s our plan for tomorrow? Are we still going to the market?",
      "How’s your schedule looking? Are we still hitting the market in the morning?",
      "Are you still game for the morning market visit?",
      "Let me know if you’re still planning to make that market trip in the morning.",
      "You still want to go to the market in the morning, right?",
      "So, any change of plans for our market trip tomorrow morning?",
      "Are we still planning for that morning visit to the market?",
      "What do you think about the market tomorrow morning? Still want to go?",
      "Just wanted to verify if you’re still good for the market in the morning.",
      "Are we still thinking about checking out that market early tomorrow?"
    ],
    [
      "Yeah, definitely! If we leave before nine, we can snag the best deals at the early stalls.",
      "For sure! The early bird gets the worm, right? Let’s aim to get there before nine.",
      "Absolutely! Leaving before nine means we can check out all the fresh produce at the top stalls.",
      "I really think it’s worth it if we make it out before nine. Those early hours are prime for the best finds!",
      "If we want the freshest picks from the market, we should really aim to leave by nine.",
      "Trust me, the early stalls are amazing. If we head out before nine, we’ll have the pick of the lot!",
      "Honestly, hitting the market before nine is a smart move. It’s way more fun when we can browse without the crowds.",
      "I can’t stress enough how worth it it is to get there early. If we leave before nine, we’ll beat the rush!",
      "I’d say let’s leave a little before nine. Those early stalls are just unbeatable for freshness.",
      "Being there before nine is a game-changer. We’d totally miss the rush and score the best goodies!",
      "Totally agree! Those early hours at the market are when all the best stuff comes in.",
      "Let’s plan to leave just before nine, yeah? The earlier we get there, the better the selection.",
      "I think we should aim to get there right before nine. The advantages of hitting those early stalls are huge.",
      "Definitely worth it if we get there early. Those stalls are just bursting with fresh items before nine!",
      "If we leave on time, we can really maximize our shopping experience at the early stalls.",
      "I love finding treasures at the market, especially when we get there before nine. It really pays off!",
      "The early market vibe is the best! We should definitely hit it before nine to take advantage.",
      "We’d be able to scope out the best selection if we leave by nine. Trust me, those stalls are well worth it!",
      "Leaving before nine is the secret sauce to a successful market trip. Let’s do it!",
      "I firmly believe we’ll have a much better experience if we hit the early stalls before nine.",
      "The earlier we get in, the better our chances of scoring the good stuff. Let’s make it happen!",
      "I can’t wait! Hitting the market early before nine will give us a real advantage at those stalls.",
      "If we set out before nine, we can really take our time exploring all the early stalls. It’ll be fun!",
      "Getting there ahead of the crowd will definitely pay off. The early stalls are where the magic happens!",
      "Those early hours make a world of difference. Let’s plan on leaving before nine to take advantage of that!",
      "I know some great stalls that are only really good if you're there early. Leaving before nine sounds perfect!",
      "Let’s be ambitious and plan on leaving before nine. Those early stalls are a treasure trove!",
      "I feel like it’s a no-brainer. If we’re aiming for the best, we should definitely get there before nine.",
      "We’ll be able to find all the freshest items if we leave just before nine. It’s so worth it!",
      "Let’s go for it! Getting to the market early really turns the whole experience up a notch.",
      "No doubt! The early stalls make the trip special. A quick departure before nine is essential.",
      "I really think it pays off to be there early. Leaving before nine will get us into those best stalls!",
      "I’m all in for the early market! Leaving before nine is the way to go if we want those goodies.",
      "It’s the early ones that have the best quality stuff. Let’s make sure to leave before nine!",
      "If we’re out the door before nine, we’ll score some awesome finds at those prime stalls.",
      "Let’s not miss out on that early magic! If we leave by nine, we’ll have the market all to ourselves.",
      "I love the thrill of the early market. Leaving before nine is such a smart move!",
      "We’ll totally enjoy the experience more if we’re there early. Those stalls are a sight before nine!",
      "I’ve found the best deals when I’ve gone early. Let’s plan to leave before nine!",
      "Definitely! The early market is where all the action is. We’ll make the most of it by leaving before nine!",
      "I think we can really make this market trip special if we leave just before nine. It’s so worth it!",
      "Let’s seize the day and hit the market before nine! Those early stalls will reward us for sure.",
      "We’ve got to leave before nine for the best experience! The early stalls are just buzzing with goodness.",
      "It’s all about the timing! If we get there before nine, we won't regret it.",
      "I just love the energy of the market in the morning! Early stalls before nine are seriously the best."
    ],
    [
      "Should we grab some fresh bread at the market, or do you think we should just bake it later?",
      "I was wondering if we should get some bread at the market, or would you rather bake our own?",
      "What do you think about picking up bread while we’re there, or do you want to make it at home?",
      "Are we thinking of getting bread from the market, or would it be better to bake it ourselves?",
      "Should we just buy some bread at the market, or is baking it later a better plan?",
      "Hey, should we consider getting bread from the market, or do you want to whip some up at home?",
      "Thinking about it, should we pick up bread there, or make our own instead?",
      "Do you think it’d be good to find some bread at the market, or should we stick to baking later?",
      "What about bread? Should we snag some at the market or bake it ourselves this time?",
      "Should we add bread to our market list, or is baking a better option for you?",
      "Are we going to get bread from the market, or are you leaning towards baking it?",
      "I can’t decide if we should just buy bread at the market or if we should bake some later.",
      "Do you want to grab bread while we’re out, or should we just bake it at home?",
      "Are we thinking about getting bread from the market, or will we just bake our own later?",
      "Should we just grab some bread at the market, or would you rather bake it later?",
      "Any thoughts on whether we should pick up bread there or make it ourselves when we get back?",
      "What do you prefer? Buying bread at the market or making it later at home?",
      "Should we just go for some fresh bread at the market, or do you want to bake instead?",
      "I’m torn about bread—should we buy it there or save the effort for another day and bake?",
      "Do you feel like we should get bread from the market, or is baking our own more appealing?",
      "So, should we keep an eye out for bread at the market, or bake some when we return?",
      "I was thinking, would it be easier to just grab bread at the market or bake later on?",
      "Would you rather skip the market bread and go straight for the baking at home instead?",
      "What’s your take on picking up bread while we’re there versus baking later?",
      "I’m curious, should we hunt for bread at the market, or do you want to do it yourself later?",
      "Should we make bread from scratch or just get some from the market to save time?",
      "Are we getting bread at the market, or are we planning to bake ours later on?",
      "Do you think buying bread at the market will be worth it, or should we just bake later?",
      "Should we stop by and get some bread at the market, or is baking later the way to go?",
      "Would it be a good idea to snag some bread at the market, or should we bake it ourselves?",
      "What if we bought some bread at the market, or do you prefer to make it ourselves?",
      "Can we think about getting the bread there, or would baking it at home be better?",
      "Hey, have you decided if we should pick some bread up at the market or bake it later?",
      "Do you want to buy some bread at the market, or do you think we’d prefer to bake it?",
      "Let’s talk about bread—should we buy some at the market or just bake later?",
      "How about we grab some bread at the market instead of baking later on?",
      "Do you think we should check for bread at the market, or just bake it when we get home?",
      "Should we plan on buying bread at the market or leave that for our baking session?",
      "I’m thinking we could get some fresh bread there; does that sound good, or are you set on baking?",
      "Would you prefer to buy bread at the market, or feel like baking some later?",
      "Are we looking to grab bread at the market, or do you have your heart set on baking instead?",
      "Maybe we should swing by the market for bread instead of baking it ourselves?",
      "What’s your vibe—buying bread there or tackling baking later?",
      "Would you like to get some bread at the market, or should we stick to baking it ourselves?",
      "Hey, should we plan on picking up bread at the market, or go for homemade later?",
      "Should we get some bread from the market, or do you prefer to whip some up later?",
      "I’m wondering, should we just buy bread at the market, or would making it ourselves be better?",
      "Are you leaning toward picking up bread there or planning to bake later?",
      "What do you think—bread from the market or fresh-baked at home later?",
      "Should we add bread to our market list, or just make it ourselves when we get back?",
      "Do you want to grab some bread while we’re at the market, or would you rather bake it?"
    ],
    [
      "I remember last time we got there, all the fresh loaves were sold out by the time we arrived.",
      "Honestly, we missed out on the best bread last week because we were running late.",
      "You know, we shouldn't risk getting there too late again; the bread was all gone before we even got a chance.",
      "The last time we were at the market, the bread section was completely empty when we finally got there.",
      "It was such a bummer last week when there were no loaves left for us.",
      "I can still picture the empty bread stand from our last trip—it was disappointing!",
      "If we want to avoid another bread fiasco like last time, we should go early.",
      "Let’s not repeat last week’s mistake; they were out of loaves before we even saw the stall.",
      "Do you recall how they sold out of bread really fast last time? We can’t let that happen again.",
      "Last time, I walked up to the bread stall and found out they were totally cleaned out.",
      "We definitely don’t want a repeat of last week; it was tough seeing all that empty space where the bread was!",
      "I’d hate to get there and find that they’ve run out again, like last time.",
      "You remember how we missed out on that amazing sourdough because we got there late?",
      "Last time, they had the best loaves, but they were already gone by the time we showed up.",
      "If we don’t get there early, it’ll be like last time when we walked away empty-handed.",
      "I still can’t believe we didn’t get any bread last time. Let’s make sure that doesn’t happen again!",
      "The early bird really does get the bread at that market; they were wiped out when we arrived last time.",
      "Let’s aim to be there on time; it was pretty sad to see the bread gone last week.",
      "I’d really hate to miss out on fresh bread again, especially after how disappointing it was last week.",
      "Just thinking about last time makes me realize we should leave even earlier this time.",
      "I don’t want to risk another bread shortage like we had last week; it was such a letdown.",
      "It’s tough not to think about last week when we showed up late and missed all the good stuff.",
      "I remember feeling so disappointed seeing that empty bread table last time we went.",
      "We definitely should prioritize getting the bread this time; last week was a total miss.",
      "If we want to guarantee some fresh bread, we better not take our time like we did last week.",
      "The fresh bread was all gone by the time we got there last time; I can't believe we let that happen!",
      "It’ll be a huge letdown if we come back empty-handed again like last week.",
      "That bread stall was bare last time we visited; we can’t afford to miss out again!",
      "I still remember how we walked past the bread stall last week only to find it was wiped out.",
      "The last trip felt like such a missed opportunity when the bread was all gone.",
      "I don’t want to have that disappointment again, like when we saw the empty bread shelf last time.",
      "Remember how bummed we were when we realized the loaves were sold out last time?",
      "To be honest, I’m a little wary of getting there late after our last experience with the bread.",
      "Let’s do our best to make it there early; last time was a clear reminder of what can happen.",
      "The bread situation last week was a real wake-up call; we can’t let that happen again.",
      "We can’t let another market trip end in disappointment like last time with the bread.",
      "It’s hard not to think about how sad it was last week when we missed the fresh loaves.",
      "I can’t stand the thought of missing out on great bread again; we need to be strategic this time.",
      "The last trip taught me a lesson about timing; it’s bread or bust!",
      "I think we should prioritize getting there early if we want to avoid running into another bread shortage.",
      "Just thinking about how we missed the loaves last time is enough motivation to get up early!",
      "Last time, the bread was a total flop for us because we were too late; let’s change that!",
      "The vibes were all off last week when we saw that there was no bread left; let’s not let it happen again!",
      "If we want to secure some fresh loaves, we should definitely make leaving a priority this time!",
      "I remember the disappointment of walking by the bread stand last time; let’s avoid that regret.",
      "Last week really opened my eyes to how quickly the good bread goes; we need a solid game plan.",
      "Trust me, we can’t let history repeat itself like last time—that bread was a total ghost!",
      "Just thinking about last time has me motivated to get up and out earlier for some fresh loaves."
    ],
    [
      "Hey, while we're at the market, do you think we should pick up anything else besides tomatoes?",
      "I was thinking, do we need to grab anything else aside from tomatoes while we're there?",
      "What do you say we keep an eye out for more than just tomatoes?",
      "Should we also look for anything extra, or is tomatoes all we need?",
      "Just to confirm, are we only getting tomatoes, or do we need anything else?",
      "I know tomatoes are on the list, but what else should we get?",
      "Is there something else you want to add to our shopping list besides tomatoes?",
      "Are we just focused on tomatoes, or should we try to find something else too?",
      "Should I keep my eyes peeled for any other goodies, or is it just tomatoes for us?",
      "Do you think we should grab anything else while we’re at it, or are we good with just tomatoes?",
      "Is there anything else we should consider picking up on our trip, besides those tomatoes?",
      "I'm wondering if there’s something else we should grab along with the tomatoes.",
      "What do you think? Any other items you want to consider while we’re out?",
      "Besides tomatoes, is there anything else we need to keep an eye out for?",
      "Are we set with just tomatoes, or would you like to add some other items to our list?",
      "While we're at the market, should we keep an eye out for anything else other than tomatoes?",
      "What do you think about adding another vegetable to our haul, or should we stick with just tomatoes?",
      "Do we want to scout for some other fresh produce, or are we sticking to just tomatoes?",
      "Should we think about other ingredients for the week, or is tomatoes all we need?",
      "I’m curious, should we add anything else to our market list while we're at it?",
      "Hey, are we just going for tomatoes, or is there something else you’d like to grab?",
      "Should I take a look for anything other than tomatoes, or are we all set with those?",
      "I was wondering if you want to add anything else to the shopping list while we’re at the market?",
      "What do you think about picking up some herbs or spices along with the tomatoes?",
      "Is there another ingredient you want to make sure we pick up while we’re there?",
      "Besides tomatoes, do we need any other essentials for the week?",
      "Are we all set with just tomatoes, or should we keep an eye out for something else?",
      "Should we think about other fruits or veggies while we're there, or just stick with tomatoes?",
      "I was thinking, are there any other staples we need to consider while shopping?",
      "Are we just going to focus on tomatoes, or do you want to add something else on the list?",
      "Hey, do we need any other staples from the market along with the tomatoes?",
      "Should we make a quick list of anything else you might want while we’re out?",
      "I’m good with just tomatoes, but let me know if you want to check for something else!",
      "What do you think about adding some fruits or greens to our shopping list too?",
      "Besides tomatoes, what's catching your eye that we should get at the market?",
      "Is there anything else you want to make sure we don’t miss while we’re shopping?",
      "Are you thinking of anything specific to grab besides the tomatoes?",
      "While we're there, is there any other produce you had in mind?",
      "Should we stop for some snacks or treats while we're at the market, or is it just tomatoes?",
      "I’d hate to miss out on something good, so do you think we should get anything else?",
      "Do you have any other cravings that we could satisfy at the market?",
      "Should we stock up on other veggies while we’re there, or just tomatoes?",
      "Let me know if there’s something else you think we should add while we're shopping.",
      "Besides tomatoes, do you have any other favorites you want to include in our haul?",
      "Should we plan for dinner ingredients while we're there, or just focus on tomatoes for now?",
      "What else can I help you remember to look for, apart from tomatoes?",
      "Are we just going with the classic tomatoes, or do you want to explore more options?",
      "Do we want to grab any snacks or treats while we're out, or just stick with our list?",
      "Is there something you love that we should definitely get alongside the tomatoes?",
      "Are there any other ingredients you think would work well with our meal plan this week?",
      "While we’re there, let’s make sure we don’t miss any surprises apart from tomatoes!",
      "Do we want to keep an open mind for other items, or just stick with our tomato plan?",
      "Should we check for any seasonal items that might go well with tomatoes?",
      "Let me know if you think of anything else we should get besides those tomatoes!",
      "Are we all set with just tomatoes, or is there more we can add to the mix?"
    ],
    [
      "We’re good on rice, but we’re totally out of lemons.",
      "I still have some rice at home, but we could really use some lemons.",
      "Oh, we’ve got plenty of rice left, but we’re fresh out of lemons!",
      "I just checked the pantry, and we could use lemons—got rice, though.",
      "We still have rice, but our lemon supply is gone.",
      "I think we've got enough rice, but we definitely need to grab some lemons.",
      "I’m set on rice, but I noticed we have no lemons in the fridge.",
      "As far as staples go, we have rice, but we’re lemon-less right now.",
      "Rice is covered, but let’s not forget to grab some lemons.",
      "I've got rice, but I'll need to pick up some lemons while we’re at it.",
      "Rice is looking good, but we could really use some lemons for cooking.",
      "We still have enough rice, but we’re almost out of lemons again.",
      "We've got rice stocked up, but we can't make that lemon vinaigrette without lemons!",
      "I’m all stocked up on rice, but we definitely need some lemons for that dish.",
      "We still have rice, but we shouldn't miss out on lemons at the market.",
      "Rice is fine, but we’re completely out of lemons; they’d really add some zing!",
      "We’re all set with rice, but we’re down to zero lemons.",
      "I checked, and we still have rice, but we should definitely grab some lemons.",
      "Rice is taken care of, but we need to replenish our lemon supply.",
      "We've got rice, but our lemon stash is looking pretty empty right now.",
      "I just realized we have enough rice, but no lemons to be found.",
      "No worries on the rice front, but we could use some fresh lemons to liven things up.",
      "Rice is good, but we could really enhance our meals with some lemons.",
      "I did a count, and we’ve got rice, but our lemons are all gone.",
      "We’re good on rice, but lemons are definitely on the shopping list.",
      "Still have rice, but we need to make sure we grab some lemons at the market.",
      "Rice is still in the pantry, but we’ve used up all our lemons, sadly.",
      "Plenty of rice left, but I’m missing lemons for that recipe we talked about.",
      "Rice is fine, but we’re in urgent need of lemons for that salad dressing.",
      "I noticed we’re still well-stocked on rice but running low on lemons.",
      "We’re set with rice, but we sure could use those lemons for flavor.",
      "I checked this morning and realized we still have rice, but we're lemon-depleted.",
      "We definitely don’t need rice, but we could really use some fresh lemons.",
      "We've got rice for days, but we've used up all the lemons in the fridge.",
      "I know we have rice at home, but I think we should pick up some lemons, too.",
      "Rice is taken care of, so let’s make sure to grab some lemons while we’re out.",
      "We’re fully stocked on rice, but lemons are a must for our menu this week.",
      "I remembered we have rice, but we're out of lemons for our recipes.",
      "We’re doing okay with rice, but don’t forget the lemons; they’re a must-have!",
      "We've still got plenty of rice, but we can't overlook the lemons this time.",
      "I saw we have rice, but lemons would really complement our meals.",
      "Rice is still in the pantry, but we need to restock on lemons.",
      "I just checked the kitchen; we’re fine on rice but totally out of lemons.",
      "Rice is sorted, but we really need to grab some lemons to go with those dishes.",
      "We’re okay on rice, but let’s prioritize picking up some lemons, too!",
      "We have rice, but we’ve completely run out of lemons; we should definitely get some.",
      "I just remembered we need lemons; we're fine on rice for now.",
      "I’m all set with rice, but we definitely have to pick up some lemons for cooking.",
      "We still have rice, but it would be a shame to forget the lemons at the market!",
      "Rice, check! We need to make sure we grab lemons, though.",
      "All good with rice, but I am craving those lemons for flavor!",
      "We’re covered on rice, but we should definitely not skip the lemons."
    ],
    [
      "Are you thinking we should cook at home after the market, or would you prefer to grab a bite somewhere nearby?",
      "What do you think about cooking at home with all our fresh finds, or should we go out and eat instead?",
      "I was wondering, do you want to whip up something at home, or should we treat ourselves to lunch out?",
      "Once we grab everything, are we heading back to make a meal, or do you feel like dining out for a change?",
      "Should we plan to cook after we shop, or does grabbing a meal nearby sound better to you?",
      "How about we decide if we want to cook or eat out after we see what we’ve picked up at the market?",
      "I'm curious, are you leaning towards making something at home, or would you like to find a nice place to eat?",
      "After we shop, do you want to cook together, or do you feel like going to a restaurant instead?",
      "Thinking about lunch, do you want to make something at home or check out a café nearby?",
      "Are we cooking at home, or does it sound fun to eat out instead after shopping?",
      "What do you think, do we want to prepare a meal at home with our ingredients, or go grab a bite?",
      "Shall we plan on cooking at home, or are you in the mood to eat out after the market?",
      "Do you want to have a little cooking session at home or treat ourselves to some food nearby?",
      "Once we finish at the market, do you think we should eat at home or find a spot to dine out?",
      "I’m torn between cooking up something at home and exploring a nearby eatery. What do you think?",
      "After we get our groceries, should we whip up a meal, or does eating out sound more appealing?",
      "Are we thinking of turning our market haul into dinner, or would you rather go grab some food?",
      "What’s the plan for after the market? Are we cooking, or should we check out a restaurant?",
      "Are you feeling like cooking a nice meal at home, or do you want to head out for a snack after shopping?",
      "Should we plan to cook something nice with our fresh ingredients, or is eating nearby on the table?",
      "After shopping, do you want to go home for dinner, or would you like to explore food options out?",
      "I was thinking we could either cook after we shop or find something tasty nearby. What do you prefer?",
      "Once we’re done at the market, do you want to have a cozy meal at home, or go out to eat?",
      "Are you up for cooking a nice dinner at home, or would you like to grab a bite somewhere?",
      "After getting our groceries, is it better to cook at home or try one of those new restaurants?",
      "Do you want to head back to cook something, or would you like to stop for lunch after the market?",
      "What are you in the mood for after the market? Cooking at home or dining out?",
      "After our market run, should we plan for a home-cooked meal or venture out for food?",
      "So, once we’ve gathered our goodies, do we want to cook together or get something to eat nearby?",
      "How about we figure out what to do after shopping? Are you feeling like cooking or eating out?",
      "Once we’re done at the market, do you want to experiment in the kitchen or enjoy a meal somewhere?",
      "What sounds better after a morning of shopping: cooking at home or grabbing a quick bite?",
      "Do you think we should head home to make dinner or treat ourselves to a nice meal out?",
      "I'm wondering if we should cook something at home after shopping or find a fun place to eat?",
      "What do you think about cooking at home versus eating out after we’re done at the market?",
      "After we shop, would you rather go home to cook up a feast or explore a local eatery?",
      "Should we turn our market finds into dinner at home, or would a nearby restaurant be more appealing?",
      "Once we grab our groceries, are we sticking to a home-cooked meal, or will we go out to eat instead?",
      "Are you thinking we should cook at home, or does something from a restaurant sound good after shopping?",
      "What’s your vibe after the market? Do you want to make something at home or eat out?",
      "Are you leaning towards cooking after we hit the market, or are you in the mood for a meal out?",
      "So, what do you think about cooking a nice dinner at home, or treating ourselves to a meal nearby?",
      "After shopping, should we prepare something wholesome at home or go out for a quick bite?",
      "How do you feel about cooking a meal after we shop, or do you think we should eat out instead?"
    ],
    [
      "Cooking at home sounds great, but only if we can find the countertop under all that clutter.",
      "I'm all for cooking at home, but I hope the kitchen isn’t still a disaster zone.",
      "As long as the kitchen isn’t a total mess, I’m down for a home-cooked meal.",
      "Cooking at home is a good idea, just as long as we've got a clean workspace to work with!",
      "I’d love to cook at home, but I really hope we can clean up a bit first.",
      "Home cooking is fine by me, but let’s make sure the kitchen isn't a nightmare.",
      "I’m excited to cook together, but I’m not keen on battling the chaos that’s in the kitchen right now.",
      "As long as we can clear things up first, I’m all in for cooking at home.",
      "I think cooking at home would be fun, provided we can actually find a place to prep!",
      "I’m okay with home cooking, but let’s tidy up that kitchen beforehand.",
      "If the kitchen isn’t a wreck, I’d prefer making something fresh at home.",
      "Home-cooked meals are the best, but let’s make sure we have a clean slate to start with!",
      "I’m totally on board for cooking at home; just need to see if it’s presentable first.",
      "As long as we can navigate through the mess, I’d be happy to cook at home.",
      "Home cooking sounds good, but I’d hate to trip over clutter while trying to cook!",
      "I’d love to whip something up at home, just want to ensure the mess is under control.",
      "Cooking at home is fantastic, but we definitely need to tackle that kitchen first!",
      "I’m okay with cooking at home, but we should probably clean up a bit first.",
      "If clearing the kitchen is part of our morning routine, then I’m up for cooking at home!",
      "I’m game for cooking, just as long as we can get the kitchen back into shape.",
      "Cooking sounds lovely, but can we manage the kitchen chaos before we start?",
      "I’d love to cook at home, but let’s make sure we’re not fighting through a mess first.",
      "I’m all about home cooking, just need to know if we can find our tools in that kitchen first!",
      "As long as we can set up a workable space in the kitchen, I’m all for it.",
      "Home cooking is perfect, just let’s make sure it’s not a post-war zone in there!",
      "I’d enjoy making something at home; we just need to ensure we can see the countertops!",
      "I think cooking at home could be really fun, but the kitchen situation needs some attention first.",
      "I’m totally down for a home meal, provided we can sort out that kitchen chaos!",
      "Cooking at home is a solid plan if we can clear out that clutter first.",
      "I’m excited to cook together, but we might need to channel our inner cleaning crew first!",
      "Cooking sounds awesome, but I just hope we can find room to actually cook!",
      "Unless the kitchen is a total battlefield, I’m all for cooking at home.",
      "I’d rather cook at home if we can make it an enjoyable space to work in.",
      "Home-cooked meals are always a treat, just not in a messy kitchen!",
      "I can get behind cooking at home, but first, we should really clean up a bit.",
      "Cooking is the way to go for me, just as long as we can find the floor in the kitchen!",
      "I’d prefer cooking at home, assuming we can conquer that mess first.",
      "If we can tidy up the kitchen, I’d be excited to whip something up at home.",
      "I’m up for a home-cooked meal, provided we can dig out the pans from the clutter!",
      "I love the idea of cooking at home, but hopefully, we can clear some space first!",
      "I’m all for a home-cooked feast, just need to make the kitchen a little more inviting first.",
      "Cooking at home sounds perfect, but can we get the kitchen in order first?",
      "If we can handle that kitchen mess, I’m totally on board with cooking at home!",
      "I’m ready for a home-cooked meal, but I need to know we can work in the kitchen!",
      "Cooking at home can be fun, just let’s get that kitchen looking decent first!",
      "I’d love to cook at home, provided we tackle that mess together first.",
      "Home cooking is great, just let’s double-check that the space is usable before we start!",
      "I’m happy to cook as long as we can clear off the counters first.",
      "Cooking at home is a great idea, assuming the kitchen chaos doesn't prevent us!",
      "I think cooking could be fun at home, just let’s make sure we’re not digging through clutter!",
      "I’m all in for cooking at home, as long as we can create a decent workspace first."
    ]
  ]
} as const;
