/**
 * Frozen F4 transcript. One run. Do not regenerate.
 */
export const FROZEN = {
  "start": "Shall we begin this tiny round now?",
  "argument": "10110110",
  "result": "ARGUMENT",
  "miss": null,
  "turns": [
    {
      "speaker": "A",
      "intent": "Ask how dinner went last night after they sat down.",
      "r": 1,
      "wanted": "1",
      "utterance": "Hey, how did dinner go last night? I’m really curious to hear about it.",
      "c6": 13,
      "pi": "1"
    },
    {
      "speaker": "B",
      "intent": "Say dinner was pretty good overall though the service was a little slow.",
      "r": 2,
      "wanted": "01",
      "utterance": "Pretty good, really! Just a bit frustrating with how slow the service was.",
      "c6": 37,
      "pi": "01"
    },
    {
      "speaker": "A",
      "intent": "Ask what they ended up ordering.",
      "r": 2,
      "wanted": "10",
      "utterance": "Did you try anything new or stick with your favorites?",
      "c6": 54,
      "pi": "10"
    },
    {
      "speaker": "B",
      "intent": "Mention the pasta was decent and the bread came out warm.",
      "r": 1,
      "wanted": "1",
      "utterance": "The pasta was decent, not the best I’ve had, but it was alright.",
      "c6": 39,
      "pi": "1"
    },
    {
      "speaker": "A",
      "intent": "Ask whether they stayed long once the place filled up.",
      "r": 1,
      "wanted": "1",
      "utterance": "So, did you end up staying for long after it got crowded?",
      "c6": 35,
      "pi": "1"
    },
    {
      "speaker": "B",
      "intent": "Say they left before dessert because the room got loud.",
      "r": 1,
      "wanted": "0",
      "utterance": "As soon as the room filled up, we thought it was best to leave. The noise level was unbearable for a nice meal.",
      "c6": 24,
      "pi": "0"
    }
  ],
  "candidates": [
    [
      "Hey, how did dinner go last night? I’m really curious to hear about it.",
      "Did you enjoy your dinner last night? I’ve been thinking about what you might’ve tried.",
      "So, how was dinner? I hope it turned out well and that you had a good time.",
      "What did you end up having for dinner last night? I bet it was something delicious!",
      "I was just wondering, how did your dinner go? I’d love to hear all the details.",
      "Hey, did you have a nice dinner last night? I’m eager to know what you thought!",
      "How was your dinner? I’m interested to see if it was as tasty as you expected.",
      "So, spill the beans! How did dinner turn out last night?",
      "How did you find dinner last night? Any highlights or surprises?",
      "What did you think of your dinner last night? I hope it was enjoyable!",
      "How did dinner go yesterday? I can’t wait to hear what you ended up eating!",
      "Did you end up making that thing you were thinking about for dinner?",
      "I’m curious, how did last night’s dinner go for you?",
      "What was the best part of your dinner last night? I can’t wait to hear about it!",
      "Did dinner live up to your expectations last night? I hope it was great!",
      "How’d it go with dinner last night? Did you try anything new?",
      "So, was dinner delicious last night? I’d love to hear all about it!",
      "What was on the menu for dinner last night? I’m eager to know!",
      "How did it all turn out for dinner? Any good stories from the meal?",
      "So, how was your dinner experience last night? I hope you enjoyed it!",
      "Did you have a nice time at dinner last night? Tell me everything!",
      "I’m curious about your dinner last night. How did it go?",
      "What did you think of the dinner from last night? Anything that stood out?",
      "How was everything for your dinner? I hope you had a relaxing time!",
      "Was your dinner last night as good as you hoped? I’d love to know!",
      "How did the dinner prep go last night? Did everything turn out okay?",
      "Did last night’s dinner meet your expectations? I can’t wait to hear!",
      "Was dinner tasty last night? I know you were excited about it!",
      "What was the highlight of your dinner last night? I want specifics!",
      "How’d you feel about dinner last night? Did you like what you had?",
      "Did you have fun at dinner last night? I’m curious how it turned out!",
      "What dish stole the show during dinner last night?",
      "How was the overall vibe at dinner last night? Good company?",
      "Did you enjoy your meal last night? I’m really interested to hear!",
      "How’d everything come together for dinner last night?",
      "How did it all taste? I’m curious about your dinner highlights!",
      "Was dinner last night everything you hoped it would be?",
      "Did you love your dinner last night? I want to hear all the juicy details!",
      "How was the atmosphere during dinner last night? Did it feel nice?",
      "What did you think about the dinner? Any surprises in flavor?",
      "How’s dinner from last night sitting with you today?",
      "Did you enjoy the company at dinner last night?",
      "How did you feel about the entire dinner experience? I’m all ears!",
      "What was your favorite part of dinner last night?",
      "So, dinner went well, right? Tell me what you thought!",
      "How was the meal you had last night? I’m genuinely interested!",
      "Did you try something new for dinner last night?",
      "How was last night’s dinner? I hope you have some fun stories!",
      "What dish made the biggest impression during dinner?",
      "What was the highlight of your dinner experience last night?",
      "Did everything turn out as planned for dinner?",
      "How did you find the flavors of your dinner last night?",
      "Were you happy with your dinner choice last night?",
      "What made dinner special for you last night?"
    ],
    [
      "Dinner was decent, actually. The only downside was that the service took its sweet time.",
      "It went well, thanks for asking! Just had to be a bit patient because the service was a tad slow.",
      "Overall, it was a nice meal. I just wish the service had been quicker.",
      "Dinner turned out pretty well! Just felt like we were waiting forever for things to arrive.",
      "Pretty good, really! Just a bit frustrating with how slow the service was.",
      "I enjoyed it! But man, the wait for the food felt longer than usual.",
      "It was nice, but I have to admit, the slow service put a bit of a damper on things.",
      "Dinner was good overall, though I did find myself tapping my foot while waiting for the server.",
      "It was a solid night out! The only hiccup was that the service was a little sluggish.",
      "Had a good time! Just a shame the food took longer to come out than expected.",
      "I liked what I ordered, but the slow service? Not so much.",
      "Dinner hit the spot! Just wish the service had been a bit snappier.",
      "It was quite enjoyable! If only the service hadn’t been dragging its feet a little.",
      "Really good food! Just noticed the service seemed to move at a snail’s pace.",
      "Dinner was tasty! The only bummer was the service lagging behind.",
      "It was a lovely evening! I just wish the service matched the quality of the food.",
      "Dinner went well, but honestly, we were left waiting longer than we’d like.",
      "I liked it! Just felt the staff could have picked up the pace a bit.",
      "The meal was great! The downside? The service took its time.",
      "Pretty satisfying dinner for sure! The slow service was just a minor distraction.",
      "Oh, it was nice! Just took longer to get our orders than I anticipated.",
      "Dinner was solid, though we definitely had to be patient with the service.",
      "I really enjoyed the food! But the slow service? That was a bit annoying.",
      "Had a great time! The service just didn’t keep up with the kitchen's pace.",
      "Dinner was on point! But wow, the wait for everything was tough.",
      "It was quite good! Just a little too slow on the service side for my taste.",
      "I had a lovely evening! Just a bit of a wait for our food to arrive.",
      "Dinner was good! The only hiccup was the service taking its time.",
      "It was enjoyable! Just felt like we were waiting forever for our drinks.",
      "Dinner went well, but the slow service was definitely a highlight, if you know what I mean.",
      "I really liked it! Just wish the service had kept us a bit more engaged.",
      "It turned out well! Just had to remind myself patience is a virtue with the slow service.",
      "All in all, a nice dinner! Just had to deal with some sluggish service.",
      "Dinner was great! The only issue was that it took longer to get our orders.",
      "Had a good meal! The service was just a bit poky for my liking.",
      "Dinner itself was lovely! The service, though? A bit of a drag.",
      "It was a pleasant evening! If only the service had been faster.",
      "Overall, pretty good! Just felt like we spent more time waiting than eating.",
      "I liked it a lot! But, oh boy, did the service test our patience.",
      "Dinner was good! It just felt like we were left waiting too long in between courses.",
      "Had a nice time! Just wish the service had been quicker to respond.",
      "Dinner was solid. Just a shame about the slow turnaround on food.",
      "It was enjoyable, but I could’ve done without the wait for service.",
      "Everything tasted great! But honestly, the service felt a little sluggish.",
      "Dinner was really nice, just had to wait longer than I’d hoped to get started.",
      "It was a nice dinner! Just felt the service could have been more efficient.",
      "The food was impressive! The slow service, however, was less than ideal.",
      "I had a great meal! Just wasn’t thrilled about how long it took to get everything.",
      "Dinner was good, but we definitely could have done with a faster service.",
      "A nice dining experience! Just a bit of a wait on the service end.",
      "Dinner was lovely! The only drawback? The service was a bit too relaxed for my liking.",
      "I really enjoyed it! But the slow service was a little frustrating at times."
    ],
    [
      "What did you guys end up getting to eat?",
      "So, what tasty dishes did you order?",
      "I’ve got to know, what did you choose from the menu?",
      "Did you try anything new or stick with your favorites?",
      "What was on your plate? I’m dying to hear!",
      "What did you guys decide to order in the end?",
      "I’m curious, what did you go for? Any standout dishes?",
      "What ended up being your meal of choice?",
      "Did you all order something different, or was there a consensus?",
      "What were you craving last night?",
      "I’m interested! What did you settle on for dinner?",
      "What did you eat? I need details!",
      "I love hearing about food! What did you end up ordering?",
      "So tell me, what deliciousness did you choose?",
      "What kind of food did you end up having?",
      "Did anything catch your eye on the menu?",
      "What was the highlight of your meal?",
      "What did you decide on after all that wait time?",
      "What dishes made their way to your table?",
      "Did you go for something adventurous or keep it classic?",
      "What did you guys end up feasting on?",
      "What did you order? I need to live vicariously through your meal!",
      "What were you feeling like eating when you finally ordered?",
      "What caught your attention on the menu?",
      "Any favorites from the menu that you couldn’t resist?",
      "What was the final choice for dinner?",
      "What meal did you end up having with all that waiting?",
      "Did you try any appetizers first, or did you go straight for the main course?",
      "What sounded best to you when you ordered?",
      "I’m really curious about what you had. Did you enjoy it?",
      "What did you end up diving into for your meal?",
      "What food did you pick? I want to compare notes!",
      "What was on the menu and what did you choose?",
      "Did you end up trying anything special?",
      "What did you all decide to go with?",
      "What was your meal like? Anything noteworthy?",
      "What ended up on your table?",
      "Did you order something you’d never had before?",
      "What did you pick? I love hearing about new dishes!",
      "What made it to your plate last night?",
      "What did you order? I want to hear about it!",
      "Did you all agree on something, or was it a mix?",
      "What delicious meal did you end up ordering?",
      "What did you think about the menu options?",
      "What caught your eye for dinner?",
      "What was the best thing you had last night?",
      "What did you finally choose after the wait?",
      "Did you have a favorite dish from last night?",
      "What was the standout item from your dinner?",
      "What meal did you go with in the end?",
      "I’m eager to know—what did you end up getting?",
      "What did you finally choose after all that debating?",
      "Did you get something that surprised you?",
      "What was in your dinner order? I want the juicy details!",
      "What dish did you finally settle on?"
    ],
    [
      "The pasta was decent, not the best I’ve had, but it was alright.",
      "I ended up going with the pasta, which was okay, but the bread really stole the show.",
      "You know, the pasta wasn’t anything to write home about, but the warm bread was a nice touch.",
      "I had some pasta that was decent, but the warm bread was definitely the highlight of the meal.",
      "Honestly, the pasta was just decent, but that warm bread? So good!",
      "The pasta was fine—nothing extraordinary. But, wow, the bread came out warm and fresh!",
      "I went for the pasta and it was decent, but the warm bread they brought out? Perfect.",
      "The pasta was alright, but I must say, the warm bread made everything better.",
      "I tried the pasta, and it was decent enough. The warm bread, though? That was a treat!",
      "The pasta was decent, but the real star was the warm bread they served.",
      "I got the pasta, which was decent, but the warm bread? I could’ve eaten a whole basket of that.",
      "The pasta was just decent—it didn’t blow me away. But the warm bread? So comforting!",
      "I had some pasta that was decent, but the warm bread was what really made the meal enjoyable.",
      "The pasta was decent; I didn’t mind it. But honestly, that warm bread was delightful!",
      "I tried the pasta and found it decent enough, but the warm bread was the real winner.",
      "The pasta was okay—nothing spectacular. But warm bread fresh out of the oven? Yes, please!",
      "I went for the decent pasta, but that warm bread added a cozy element to the meal.",
      "The pasta was decent, could’ve used a bit more flavor, but the warm bread was spot on!",
      "The pasta was pretty decent. They served warm bread, which was just what I needed.",
      "I ended up with the pasta, which was decent, but alas, the warm bread saved the day.",
      "The pasta was decent. I can’t complain too much with that warm bread on the table.",
      "I went with the pasta, and honestly, while it was decent, that warm bread stole the spotlight.",
      "I had decent pasta, but wow, that warm bread was an unexpected delight!",
      "The pasta didn’t impress me much, but I really enjoyed the warm, fresh bread.",
      "I had some decent pasta, but it was the warm bread that truly won my heart.",
      "The pasta was decent enough, but I could have feasted on that warm bread all night.",
      "I opted for the pasta, and it was decent, but the warm bread was what I craved.",
      "The pasta was okay, but I’ve got to hand it to them for the warm bread—it was flawless.",
      "I found the pasta to be decent, but the warm bread was definitely a highlight of the evening.",
      "The pasta was alright—not bad, not great. The warm bread, though? Perfectly toasted!",
      "I had some decent pasta, but nothing compared to the joy of that warm bread.",
      "I tried the pasta—it was decent, but let me tell you, the warm bread was amazing.",
      "I went with the pasta, which was decent—it did the job. The warm bread, however? Delightful.",
      "The pasta was decent, nothing spectacular, but that warm bread was just what I needed.",
      "I had decent pasta, but the real treat was the warm bread that came with it.",
      "I tried the pasta, and while it was decent, that warm bread was quite a surprise!",
      "The pasta was decent, but the warm bread was definitely the MVP of the meal.",
      "I had decent pasta. The real standout was the warm bread that came out fresh from the oven.",
      "I went for pasta, and while it was decent, the warm bread was deliciously comforting.",
      "I ended up with decent pasta; the highlight for me was definitely that warm bread.",
      "The pasta was decent enough, but the warm bread was something special.",
      "I chose the pasta and found it to be decent, but that warm bread? Absolutely delightful!",
      "The pasta was decent, but the warm bread was so good I could have made a meal of it.",
      "The pasta didn’t blow me away, but the warm bread really brightened up my night.",
      "I had decent pasta that didn’t really excite me, but the warm bread made up for it.",
      "I found the pasta to be decent, but it was the warm, fresh bread that really hit the spot.",
      "I went with the pasta, which was decent, but that warm bread? Totally hit the mark!",
      "The pasta was okay, but the warm bread? Now that was something I’ll remember!",
      "I had some decent pasta, but they really knocked it out of the park with the warm bread.",
      "The pasta I had was decent, but warm bread always makes a meal feel special, doesn’t it?",
      "I tried the decent pasta, and while it wasn’t great, the warm bread was a delightful surprise!"
    ],
    [
      "So, did you end up staying for long after it got crowded?",
      "How about the atmosphere once more people came in? Did it feel different?",
      "Once things filled up, did you guys stick around or head out?",
      "Did the crowd change the vibe, or was it still a nice place to be?",
      "I’m curious, did you hang out there long after it got busier?",
      "How did the restaurant feel once it started getting full?",
      "Did you decide to stay, or was it too chaotic once the place filled up?",
      "So, what was it like when the restaurant got packed? Did you all stay?",
      "Did the bustling crowd make you want to leave sooner than planned?",
      "When the place got busy, did you all just sit tight or make a move?",
      "Did you find yourselves lingering at the table, or was it too hectic?",
      "So, did it get so crowded that you wanted to get out of there?",
      "Did you enjoy being there even with more people around, or not so much?",
      "Was it fun to stick around, or did you feel ready to leave once it got busy?",
      "Once it filled up, did you all decide to hang out for a bit longer?",
      "Did the full restaurant make it hard to enjoy your meal, or was it fine?",
      "I wonder, did you stay long enough to see how the service changed with more diners?",
      "Once the crowd rolled in, were you guys still comfortable at your table?",
      "Did you find a cozy spot, or did the crowd make it feel a bit too cramped?",
      "So, knowing it got busier, did you and your friends linger over dessert?",
      "What did you think about the atmosphere once more diners arrived?",
      "When it got busy, did you end up feeling rushed to leave?",
      "Did you stick around to see how they handled the rush, or was it too much?",
      "After the place filled up, did it feel more relaxed or just chaotic?",
      "How did you feel about staying longer once the restaurant started filling up?",
      "Once it got crowded, did you guys want to keep chatting or call it a night?",
      "Was the energy good when it got fuller, or did it change the mood?",
      "Did it take a lot longer to get attention from the servers as it filled up?",
      "Did you all want to enjoy your time more, or was it time to split once it got busy?",
      "Did the restaurant still feel like a nice place to be with all those people?",
      "How did the food experience change when everyone else started showing up?",
      "Did a full restaurant impact your decision to stay longer at the table?",
      "How did you find the service once the place started getting packed?",
      "What was it like hanging out there once it became so crowded?",
      "Did the crowd add to the fun, or did it feel overwhelming?",
      "Was it hard to have a conversation with the place getting so busy?",
      "Did you feel tempted to leave once the crowd arrived, or did you stay put?",
      "Once it filled up, did the service slow down even more?",
      "Did being surrounded by people change how you felt about the meal?",
      "Did you end up enjoying the busyness, or was it more of a hassle?",
      "Did the atmosphere shift when more customers came in, or was it fun?",
      "So, did the restaurant's energy keep you there longer than expected?",
      "How did the crowded space make you feel about staying for dessert?",
      "Did it feel like a long wait once more people sat down, or was it smooth?",
      "Once it got busy, did it take away from your overall experience?",
      "Was the crowd enjoyable, or did you find it a bit too much?",
      "How did the vibe change when it got full? Did it affect your plans?",
      "Did you guys end up chatting more or rushing when it got busy?",
      "So, did you decide to stick around longer because of the excitement?",
      "Once the restaurant filled up, what did you all think about sticking around?",
      "Did more diners create a lively atmosphere, or was it too loud for you?",
      "Did you feel like staying was the right choice even with the crowd?",
      "How did you manage your time there as the restaurant got busier?",
      "Was it hard to relax once the place was full, or did you enjoy it?",
      "Did you think about leaving once it filled up, or were you good where you were?"
    ],
    [
      "Yeah, we left before dessert. The place got so loud that it felt chaotic.",
      "Honestly, we decided to skip dessert and head out early. The noise was just too much.",
      "We called it a night before dessert since it got really crowded and noisy.",
      "It was so packed that we couldn't even hear each other talk, so we figured it was time to go.",
      "As soon as the room filled up, we thought it was best to leave. The noise level was unbearable for a nice meal.",
      "We ended up departing before dessert because it became one of those loud atmospheres.",
      "The ambiance turned hectic, so we left before dessert. It just wasn’t enjoyable anymore.",
      "Once it got loud, we didn’t want to stick around for dessert. It felt a bit overwhelming.",
      "We actually left before dessert hit the table. It just got so loud in there.",
      "The crowd made the vibe way too chaotic, so we took off before dessert came out.",
      "With all the noise, we figured we’d just skip dessert and call it a night.",
      "It was getting rowdy, so we opted to leave before indulging in anything sweet.",
      "The noise really killed the mood, so we cut our losses and left before dessert.",
      "Before we knew it, it had gotten so loud that we decided to head out instead of waiting for dessert.",
      "We bolted before dessert because the noise was just escalating too much.",
      "It got so raucous that sticking around for dessert felt pointless. We left early.",
      "Dessert wasn’t happening for us; the room was just too loud and lively.",
      "We skipped dessert due to the noise. It was like a restaurant filled with partygoers.",
      "The din in the restaurant made it hard to enjoy our meal, so we left before dessert.",
      "I knew it was time to go when the crowd grew and dessert was on its way.",
      "We didn’t want to deal with the loud atmosphere any longer, so we left before dessert.",
      "The place turned into a bit of a circus, so we decided to leave without dessert.",
      "By the time dessert was coming, the noise made it uncomfortable, so we just left.",
      "We made an early exit before dessert since it got really congested and boisterous.",
      "When it started getting loud, it just felt right to leave before dessert arrived.",
      "We ducked out before dessert because I couldn't stand the noise anymore.",
      "The atmosphere turned chaotic, so we figured it was best to leave before dessert.",
      "Honestly, we just couldn’t handle the noise any longer, so we skipped dessert.",
      "The commotion was overwhelming, and we chose to leave instead of waiting for dessert.",
      "We said goodbye to dessert because the noise level was just ridiculous.",
      "We opted out of dessert since the loudness was just too much to bear.",
      "The loud chatter made it hard to relax, so we decided to leave before we got dessert.",
      "Dessert wasn't in the cards for us; the noise was really distracting by the end.",
      "We left dessert behind because the room became so loud and busy.",
      "As soon as it got loud, we figured dessert was overrated and left.",
      "The atmosphere turned into a bit of a mess, so we skipped dessert and headed home.",
      "With all the noise, we had to leave before dessert. It just wasn't worth it.",
      "We missed dessert because the noise was just too intense to enjoy it.",
      "The energy in the room shifted to chaos, so we left before dessert, feeling it was right.",
      "We thought it best to skip dessert; the place felt like a crowded party by then.",
      "We could hardly hear ourselves think, so we left before dessert arrived.",
      "The volume in the restaurant really increased, so we headed out before dessert.",
      "We skipped dessert entirely because the place got so loud we couldn’t even chat.",
      "The noise really picked up, and we didn't want to be stuck waiting for dessert.",
      "Honestly, it got so loud that dessert just felt like an afterthought, so we left.",
      "We decided not to wait for dessert since it turned into such a loud scene.",
      "We made a quick exit before dessert since the noise was just too much.",
      "The place turned into a bit of a zoo, and we chose to leave before dessert."
    ]
  ]
} as const;
