/**
 * Frozen F9 joint transcript. One run. Do not regenerate.
 */
export const FROZEN = {
  "map": "half3",
  "bits": "10110",
  "result": "JOINT",
  "miss": null,
  "turns": [
    {
      "speaker": "A",
      "intent": "Ask whether they still want to walk after work tonight.",
      "mode": "SKIP",
      "bits": "",
      "next": "DATA",
      "utterance": "Hey, are we still on for that walk after work tonight?",
      "c6": 24
    },
    {
      "speaker": "B",
      "intent": "Say the shorter loop is fine if it stays dry.",
      "mode": "DATA",
      "bits": "10",
      "next": "SKIP",
      "utterance": "If it doesn’t rain, I think the shorter loop would be great.",
      "c6": 49
    },
    {
      "speaker": "A",
      "intent": "Ask if they should bring a jacket this time.",
      "mode": "SKIP",
      "bits": "",
      "next": "DATA",
      "utterance": "Do you think we should bring jackets this time?",
      "c6": 23
    },
    {
      "speaker": "B",
      "intent": "Say last week they were fine until the wind picked up near the hill.",
      "mode": "DATA",
      "bits": "11",
      "next": "DATA",
      "utterance": "The weather was nice until that strong gust came our way at the hill last week.",
      "c6": 20
    },
    {
      "speaker": "A",
      "intent": "Suggest meeting by the usual gate around six.",
      "mode": "DATA",
      "bits": "0",
      "next": "SKIP",
      "utterance": "What do you think about meeting by the usual gate at six?",
      "c6": 54
    }
  ],
  "candidates": [
    [
      "Hey, are we still on for that walk after work tonight?",
      "I was just thinking about our walk later—are we still good to go?",
      "What do you think? Still up for a stroll after we wrap up at work?",
      "Just checking in—do you still want to take that walk tonight after work?",
      "Are you still feeling like going for a walk after we finish working?",
      "I hope you’re still down for a walk tonight after work!",
      "So, are we still planning to head out for a walk later?",
      "Hey, just wanted to see if you're still interested in that walk this evening.",
      "Do you still want to go for a walk after we clock out?",
      "I know we talked about walking after work—are you still up for that?",
      "Hey, are you still thinking about hitting that trail after work?",
      "Just curious, do you still want to take a walk after we finish up today?",
      "Are we still on for that walk tonight, or have plans changed?",
      "I’m looking forward to our walk later! Are you still in?",
      "So, how do you feel about going for a walk after work tonight?",
      "Just checking to see if you still want to walk this evening.",
      "Hey, are we still planning on that walk after work?",
      "I was thinking about our walk—are you still up for it after we finish?",
      "What do you say, still interested in taking that walk tonight?",
      "Are you still keen on going for a walk after work wraps up?",
      "Just wanted to confirm—are we still walking tonight?",
      "I hope you’re still game for that walk after work!",
      "Is that walk still on your radar after we finish?",
      "Hey! Are we still doing that walk after work today?",
      "Do you still want to go for a walk after we get off?",
      "What do you think—still on for a walk after work?",
      "I was wondering if you still wanted to go for a stroll later this evening.",
      "Are you still feeling up to that walk after work tonight?",
      "What's the plan for later? Still up for a walk after we finish?",
      "Hey, any thoughts on the walk after work? Still interested?",
      "I hope you’re still down for a walk later today!",
      "Are we still set for our walk after we finish working?",
      "Just wanted to see if you were still thinking about heading out for that walk.",
      "Are you still planning on walking after work tonight?",
      "How do you feel about that walk after we finish up for the day?",
      "Do you still want to walk tonight after we’re done here?",
      "Let me know if you’re still up for that walk later!",
      "What do you think? Are we still on for that walk after work?",
      "I’d love to go for a walk tonight if you’re still up for it.",
      "So, do we have a walking plan for later on?",
      "Are you still excited about our walk after work?",
      "Are we still planning that walk after work today?",
      "Hey, just checking in—are we still good for a walk this evening?",
      "Would you still like to take that walk after work?",
      "Are we still thinking about heading out for a walk tonight?",
      "Just wanted to confirm—are you still interested in walking later?",
      "What do you feel about that walk after work—still on?",
      "Hey there! Are you still good for that walk tonight?",
      "Are you still interested in a stroll after we finish work?",
      "Is the walk after work still on the agenda for you?",
      "Hey! Is that walk still happening tonight after work?",
      "Would you still like to go for that walk after we finish working?",
      "Are we still set for that evening walk after work?"
    ],
    [
      "Yeah, the shorter loop sounds good to me, as long as the weather holds up.",
      "I’m okay with the shorter route if it stays dry out there.",
      "If the rain stays away, I'm down for the shorter loop.",
      "Let’s plan on the shorter one then, provided it doesn't rain.",
      "I think the shorter loop is perfect, assuming the weather cooperates.",
      "As long as it's not too wet, I'm fine with just doing the shorter loop.",
      "If it's dry, I’d prefer the shorter route tonight.",
      "I’m good with the shorter loop, just hoping it doesn’t rain.",
      "The shorter loop's cool with me, but I don’t want to mess with wet trails.",
      "I’m all for the shorter route tonight, as long as we don’t get soaked.",
      "Let’s do the shorter one if it stays nice out.",
      "If it doesn’t rain, I think the shorter loop would be great.",
      "I’d say the shorter loop works, but let’s hope the weather stays clear!",
      "The shorter route is fine with me, as long as we don’t have to dodge puddles.",
      "I’m happy with the shorter loop if the skies stay clear.",
      "If it’s dry, I’m all in for the shorter walk.",
      "A quick loop sounds good, but let’s keep an eye on the weather.",
      "If it’s dry when we’re done with work, how about we just do the shorter loop?",
      "I can do the shorter loop, but only if the rain stays away!",
      "I’m fine with the shorter route tonight as long as it doesn't pour.",
      "As long as the weather is nice, I’m totally okay with the shorter loop.",
      "Let’s keep it to the shorter one if it stays dry, that works for me!",
      "I’d prefer the shorter loop, but fingers crossed for dry weather!",
      "We can stick with the shorter loop as long as it's not too soggy out.",
      "Provided it stays dry, I’m on board with the shorter loop.",
      "The shorter one works if we don’t have to deal with any rain.",
      "If the weather holds, I’m good for the shorter loop tonight.",
      "Let’s aim for the shorter loop, as long as it doesn’t rain on us.",
      "I’d love to take the shorter route if the weather holds up!",
      "The shorter path sounds great if the rain stays away.",
      "I’m okay with just doing the shorter loop if it’s dry when we go out.",
      "Assuming the weather is good, I’m all for the shorter route.",
      "Let’s do the shorter loop if the rain stays out of the picture.",
      "I’m for the shorter route if it’s dry, that’ll work!",
      "If the weather stays nice, I’m totally up for the shorter loop.",
      "The shorter loop sounds perfect, but let’s hope for no rain!",
      "If it stays nice out, I’ve got no problem with the shorter distance.",
      "The shorter loop works for me, provided it's dry outside.",
      "We can definitely take the shorter loop if it stays clear tonight.",
      "I’d be happy with the shorter route, just as long as it doesn’t rain.",
      "I'm game for the shorter loop if the weather is pleasant.",
      "Let’s keep it short tonight, as long as it’s not pouring!",
      "If it stays dry, the shorter loop will be perfect for us.",
      "I’m fine with the shorter loop, as long as the weather is on our side.",
      "We can go with the shorter route if the rain holds off.",
      "If it’s dry, I’d prefer the shorter loop for tonight’s walk.",
      "The shorter loop is good for me, assuming we get lucky with the weather.",
      "Let’s stick with the shorter loop if it stays dry, I’m all for it!",
      "I’ll go for the shorter route as long as it’s not too wet out.",
      "The shorter loop works if we can dodge the rain, I’m down!",
      "I’m good with the shorter walk, hoping the rain doesn’t come.",
      "If the rain isn’t a problem, I’m definitely in for the shorter loop."
    ],
    [
      "Do you think we should bring jackets this time?",
      "Should we be safe and pack a jacket, just in case?",
      "What about a light jacket? I feel like it could get chilly later.",
      "Do you reckon we might need to layer up with a jacket tonight?",
      "I was wondering if I should grab a jacket. What do you think?",
      "Should I bring a jacket or do you think it’ll stay warm?",
      "Hey, want to take jackets just in case it cools down?",
      "I’m debating whether or not to take a jacket. What’s your vibe?",
      "Are you thinking of wearing a jacket, or is it going to be warm enough?",
      "Should I throw a jacket in the car, just in case we need it?",
      "I don't want to freeze, should we bring jackets for the walk?",
      "Maybe we should both bring jackets, you know, just to be prepared.",
      "What do you think? Will it be jacket weather tonight?",
      "I'm thinking I might bring a jacket. What do you think about that?",
      "Should we be cautious and pack jackets for the evening?",
      "Are jackets a good idea tonight? I don’t want to be cold!",
      "If it's cloudy, I might want a jacket. What do you think?",
      "I’ve got a feeling it could get chilly. Should I bring a jacket?",
      "Do we need jackets tonight, or are we good with just sweaters?",
      "Would you mind if I brought a jacket along? Just in case, you know?",
      "I’m considering taking a light jacket. What are your thoughts?",
      "Should we both plan on wearing jackets, or is that overkill?",
      "Do you think a jacket is necessary for our walk, or will it be fine?",
      "I can grab a jacket if you think it's going to be cooler.",
      "What do you say about jackets? Better safe than sorry, right?",
      "Are you planning to wear a jacket? I might just follow your lead!",
      "I can’t decide if a jacket will be needed. What’s your prediction?",
      "How about we both take jackets, just to stay on the safe side?",
      "A jacket might be a wise choice. Want to bring some?",
      "Do we want jackets for later, or will it be too warm?",
      "I was thinking about a jacket. Do you think it's wise?",
      "Should I wear a jacket on our walk? I'm good either way!",
      "What do you think? A jacket could really help if it gets chilly, huh?",
      "Is it going to be warm enough, or should I bring a jacket just to be sure?",
      "I’m on the fence about jackets. What’s your take on it?",
      "Maybe I’ll pack a jacket, just in case the temperature drops.",
      "Want to take jackets? I’d hate to be cold while we walk.",
      "I'm leaning toward bringing a jacket. What do you suggest?",
      "How about we plan on jackets? You never know with the weather!",
      "I know it’s warm now, but should we still consider jackets?",
      "What do you think? A jacket could be a smart move for tonight.",
      "Should I plan on taking a jacket? I just want to be comfy!",
      "If it cools off, I’d be glad I grabbed a jacket. You think it's a good idea?",
      "Will it be cool enough for a jacket after the sun sets?",
      "I mean, a jacket wouldn’t hurt, right? Just in case?",
      "Should I toss a jacket in my bag, or do you think we'll be good without?",
      "What’s your instinct on the whole jacket situation? Better to bring one, right?",
      "I don’t want to get caught in the cold. Maybe we should bring jackets?",
      "Do you feel like a jacket is necessary for tonight’s adventure?",
      "Should we reconsider and bring jackets for a cozy walk?"
    ],
    [
      "Yeah, last week we were good until the wind hit us on the hill.",
      "I remember we were fine for most of it, but that gust was something else.",
      "Honestly, we didn’t need jackets until the wind picked up by the hill last time.",
      "Last week was alright until we hit that exposed spot near the hill and the breeze kicked in.",
      "I think we were fine at first, but the wind caught us off guard when we reached the hill.",
      "We probably should’ve had jackets last week; I was fine until the wind kicked in by the hill.",
      "The walk was nice until the wind picked up sharply near that hill.",
      "We didn’t even think about jackets until we got hit by that chilly wind at the hill last week.",
      "Last week’s walk was pleasant until that unexpected wind hit us near the hill.",
      "The weather was nice until that strong gust came our way at the hill last week.",
      "I felt comfortable until the wind swirled around us by the hill last week.",
      "We were doing great until we reached that hill where the wind just whooshed in.",
      "Last time, we could have used jackets when the wind picked up at that one spot.",
      "It was going smoothly until we hit the hill and the wind decided to join us.",
      "We might want to think about jackets since last week’s wind at the hill was pretty rough.",
      "I mean, we had a great time until that wind kicked in by the hill.",
      "If I remember correctly, it was nice until we hit that windy part near the hill last week.",
      "That wind near the hill really caught us off guard last week, didn't it?",
      "I think we underestimated how cold it could get by that hill with the wind last week.",
      "Last week, my cozy vibe ended when the wind picked up out of nowhere near the hill.",
      "We were enjoying ourselves until that strong wind came blasting through near the hill.",
      "I felt great until the wind really whipped up near the hill during our last walk.",
      "Honestly, that windy patch by the hill surprised us last week, didn't it?",
      "Yeah, we were fine most of the time, but that wind near the hill was a game changer.",
      "We were laughing and chatting until that chilly wind swept through by the hill.",
      "Last week, the walk was lovely until the wind came barrelling through on the hill.",
      "I didn’t think we’d need jackets until the wind really started howling near the hill.",
      "The breeze caught us off guard, especially by that exposed hill last week.",
      "Remember how we were just enjoying our walk until the wind picked up near the hill?",
      "I didn’t foresee that wind situation last week until we got near the hill.",
      "Last week was fun, but that gust near the hill was a bit too much for me.",
      "I recall feeling pretty warm until that ridiculous wind decided to hit us by the hill.",
      "We should definitely be prepared this time since the wind surprised us at the hill last week.",
      "That spot by the hill really needs a jacket warning based on last week’s experience.",
      "It was a nice evening until that wind from the hills put a chill in the air last week.",
      "I felt like we were in good shape until that wind whipped around us when we reached the hill.",
      "Last week, it was all good vibes until we faced that wind situation by the hill.",
      "That wind caught us by surprise last week, especially at the hill part.",
      "We had a delightful time until we hit that windy stretch near the hill last week.",
      "The weather seemed fine until that windy blast caught us off guard at the hill.",
      "Last week was decent until the wind blew in fiercely when we got to the hill.",
      "We were definitely enjoying ourselves until that sudden gust came in from the hill last week.",
      "The moment we reached the hill, the wind just roared in unexpectedly last week.",
      "I thought it was a perfect evening until that hill wind turned up the chill factor.",
      "Let’s not forget how the wind shifted last week when we got to that hill section.",
      "It would be smart to pack jackets since last week’s hill wind was quite surprising.",
      "Last week was lovely until the wind disturbed our tranquility near the hill.",
      "Honestly, I didn’t expect the hill wind to be that much of a game-changer for us last week.",
      "I think a jacket this time might save us from that chilly hill wind we faced last week.",
      "Last week’s walk was enjoyable, except for the wind that tried to steal the show by the hill.",
      "I remember being warm until we got to that spot where the wind decided to blow.",
      "I thought we’d be fine, but that wind really gave us a run for our money near the hill last week.",
      "It’s funny how we were so comfortable until that wind burst in near the hill last week."
    ],
    [
      "How about we meet at the usual gate around six?",
      "Let's say we rendezvous at our usual spot by six then.",
      "Why don’t we plan to meet at the usual gate at six?",
      "I was thinking we could just meet by the usual gate at around six.",
      "Let’s stick to our usual gate around six, sound good?",
      "I can be at the usual gate by six if that works for you.",
      "What do you think about meeting by the usual gate at six?",
      "How does meeting at our usual gate at six sound to you?",
      "I propose we meet at the usual gate around six.",
      "Let’s catch up at the usual gate, say six o’clock?",
      "I’ll be at the usual gate around six, just like last time.",
      "How about the usual gate at six tonight?",
      "We should stick to the plan and meet at the usual gate by six.",
      "I suggest we meet where we usually do, around six.",
      "Let's meet at the familiar gate around six, yeah?",
      "What if we just meet at our regular spot around six?",
      "I think meeting at the usual gate at six would work perfectly.",
      "How about I see you at the usual gate around six?",
      "Let’s go with our tradition and meet at the usual gate by six.",
      "Would you be okay meeting at the usual gate at six?",
      "What do you think about the usual gate at six this evening?",
      "I reckon meeting at the usual gate by six is a solid plan.",
      "Why not make it six at our usual gate, then?",
      "Just like before, let’s meet at the usual gate around six.",
      "Are we good to meet by the usual gate at six as usual?",
      "What time shall we meet at the usual gate? How about six?",
      "Let’s not change a good thing; see you at the usual gate at six!",
      "If it’s all right, I’d love to meet at the usual gate around six.",
      "Let’s do six at the usual gate. Keeps it simple!",
      "I’ll head over to the usual gate around six; I hope you can make it!",
      "How about we meet at that usual gate of ours, say six o'clock?",
      "I think six at our usual gate will work out nicely.",
      "Why don’t we aim for the usual gate at six?",
      "I like the idea of meeting at our regular spot at six.",
      "Shall we say the usual gate at six?",
      "I’m thinking the usual gate by six should be good for us.",
      "Let’s just meet where we always do, around six tonight.",
      "How about I meet you at our usual gate around six?",
      "I’ll plan on being at the usual gate at six, if that’s cool.",
      "Shall we stick to the familiar gate at six?",
      "Let’s keep it classic and meet at the usual gate by six.",
      "What do you say we meet by the usual gate at six?",
      "I’ll swing by our usual gate at six, hope to see you there!",
      "I’ll be waiting at the usual gate around six, as always.",
      "Are we on for six at the usual gate?",
      "Let’s plan on our usual spot at six; it’s been a while.",
      "I’ll see you at the usual gate at six. Does that work for you?",
      "How does six at our usual gate fit into your plans?",
      "Let’s meet at the usual gate at six, and we’ll go from there.",
      "I’m thinking six at the usual gate would be ideal.",
      "I propose we meet at our usual gate around six; what do you think?",
      "Let’s keep the tradition alive and meet by the usual gate at six!",
      "Let’s do the usual routine and meet at the gate around six.",
      "Sound good if we meet at the usual gate at six?",
      "Let’s aim for our usual meeting place at six."
    ]
  ]
} as const;
